// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 9.1.0
// Project name: SquareLine_Project2

#include "ui.h"
#include "ui_helpers.h"

///////////////////// VARIABLES ////////////////////

const struct Configs *configuracionesUI_ = &configuraciones;
const int32_t *alarmasUI_ = &alarmas;
const estadoControl_t* estadoControlUI_;



// SCREEN: ui_Inicio
void ui_Inicio_screen_init(void);
lv_obj_t * ui_Inicio;
lv_obj_t * ui_LogoInicio;
lv_obj_t * ui_LabelInicio;


// SCREEN: ui_Apagado
void ui_Apagado_screen_init(void);
lv_obj_t * ui_Apagado;
void ui_event_ButtonEncendidoGrande(lv_event_t * e);
lv_obj_t * ui_ButtonEncendidoGrande;
lv_obj_t * ui_LabelSimboloPower2;
void ui_event_ButtonAlarma2(lv_event_t * e);
lv_obj_t * ui_ButtonAlarma2;
lv_obj_t * ui_LabelSimboloAlarma2;
void ui_event_ButtonReset(lv_event_t * e);
lv_obj_t * ui_ButtonReset;
lv_obj_t * ui_LabelSimboloReset;
lv_obj_t * ui_ImageLogoFlowing3;


// SCREEN: ui_Principal
void ui_Principal_screen_init(void);
void ui_event_Principal(lv_event_t * e);
lv_obj_t * ui_Principal;
void ui_event_PanelConfiguraciones(lv_event_t * e);
lv_obj_t * ui_PanelConfiguraciones;
lv_obj_t * ui_LabelSPAcs;
lv_obj_t * ui_LabelSPCal;
lv_obj_t * ui_LabelTempSPAcs;
lv_obj_t * ui_LabelTempSPCal;
lv_obj_t * ui_LabelSimboloConfiguracion;
lv_obj_t * ui_PanelValores;
lv_obj_t * ui_ArcTemperatura;
lv_obj_t * ui_LabelTemperatura;
lv_obj_t * ui_LabelPresion;
lv_obj_t * ui_ImageCal;
lv_obj_t * ui_ImageAcs;
void ui_event_ButtonAlarma(lv_event_t * e);
lv_obj_t * ui_ButtonAlarma;
lv_obj_t * ui_LabelSimboloAlarma;
void ui_event_ButtonEncendido(lv_event_t * e);
lv_obj_t * ui_ButtonEncendido;
lv_obj_t * ui_LabelSimboloPower;
lv_obj_t * ui_ImageLogoFlowing;
void ui_event_PanelAlarmas(lv_event_t * e);
lv_obj_t * ui_PanelAlarmas;
lv_obj_t * ui_LabelAlarma;
lv_obj_t * ui_LabelDiagnosticoPrincipal;


// SCREEN: ui_Alarmas
void ui_Alarmas_screen_init(void);
void ui_event_Alarmas(lv_event_t * e);
lv_obj_t * ui_Alarmas;
lv_obj_t * ui_Label16;
lv_obj_t * ui_Alarma1;
lv_obj_t * ui_Alarma2;
lv_obj_t * ui_Alarma3;
lv_obj_t * ui_Alarma4;
lv_obj_t * ui_Alarma5;
lv_obj_t * ui_SinAlarma;
void ui_event_ButtonVolverAlarmas(lv_event_t * e);
lv_obj_t * ui_ButtonVolverAlarmas;
lv_obj_t * ui_LabelVolverAlarmas;
void ui_event_ImageLogoConfigsUsuario2(lv_event_t * e);
lv_obj_t * ui_ImageLogoConfigsUsuario2;
void ui_event_Button1(lv_event_t * e);
lv_obj_t * ui_Button1;
lv_obj_t * ui_Label2;


// SCREEN: ui_Alertas
void ui_Alertas_screen_init(void);
lv_obj_t * ui_Alertas;
lv_obj_t * ui_Panel4;
lv_obj_t * ui_LabelError;
lv_obj_t * ui_LabelAclaracion;
void ui_event_ButtonVovler2(lv_event_t * e);
lv_obj_t * ui_ButtonVovler2;
lv_obj_t * ui_Label12;
lv_obj_t * ui_ImageLogoFlowing2;


// SCREEN: ui_ConfiguracionesUsuario
void ui_ConfiguracionesUsuario_screen_init(void);
void ui_event_ConfiguracionesUsuario(lv_event_t * e);
lv_obj_t * ui_ConfiguracionesUsuario;
lv_obj_t * ui_Container1;
void ui_event_CalefacionMas(lv_event_t * e);
lv_obj_t * ui_CalefacionMas;
lv_obj_t * ui_Label4;
void ui_event_CalefaccionMenos(lv_event_t * e);
lv_obj_t * ui_CalefaccionMenos;
lv_obj_t * ui_Label5;
void ui_event_SpinboxCalefaccion(lv_event_t * e);
lv_obj_t * ui_SpinboxCalefaccion;
lv_obj_t * ui_Container2;
void ui_event_ACSMas(lv_event_t * e);
lv_obj_t * ui_ACSMas;
lv_obj_t * ui_Label19;
void ui_event_ACSMenos(lv_event_t * e);
lv_obj_t * ui_ACSMenos;
lv_obj_t * ui_Label13;
void ui_event_SpinboxACS(lv_event_t * e);
lv_obj_t * ui_SpinboxACS;
lv_obj_t * ui_ImageConfigAcs;
void ui_event_ButtonVolverConfiguracionUsuario(lv_event_t * e);
lv_obj_t * ui_ButtonVolverConfiguracionUsuario;
lv_obj_t * ui_LabelVolverConfiguracionUsuario;
void ui_event_ButtonCalefaccion(lv_event_t * e);
lv_obj_t * ui_ButtonCalefaccion;
lv_obj_t * ui_ImageConfigCalefaccion;
void ui_event_ImageLogoConfigsUsuario(lv_event_t * e);
lv_obj_t * ui_ImageLogoConfigsUsuario;
lv_obj_t * ui_LabelTituloConfigsUsuario;


// SCREEN: ui_ConfiguracionesAvanzadas
void ui_ConfiguracionesAvanzadas_screen_init(void);
void ui_event_ConfiguracionesAvanzadas(lv_event_t * e);
lv_obj_t * ui_ConfiguracionesAvanzadas;
lv_obj_t * ui_ContainerSpinbox1;
void ui_event_botonMasSpinbox1(lv_event_t * e);
lv_obj_t * ui_botonMasSpinbox1;
lv_obj_t * ui_LabelMasSpinbox1;
void ui_event_botonMenosSpinbox1(lv_event_t * e);
lv_obj_t * ui_botonMenosSpinbox1;
lv_obj_t * ui_LabelMenosSpinbox1;
void ui_event_Spinbox1(lv_event_t * e);
lv_obj_t * ui_Spinbox1;
lv_obj_t * ui_ContainerSpinbox2;
void ui_event_botonMasSpinbox2(lv_event_t * e);
lv_obj_t * ui_botonMasSpinbox2;
lv_obj_t * ui_LabelMasSpinbox2;
void ui_event_botonMenosSpinbox2(lv_event_t * e);
lv_obj_t * ui_botonMenosSpinbox2;
lv_obj_t * ui_LabelMenosSpinbox2;
void ui_event_Spinbox2(lv_event_t * e);
lv_obj_t * ui_Spinbox2;
void ui_event_ButtonCambioDerecha(lv_event_t * e);
lv_obj_t * ui_ButtonCambioDerecha;
lv_obj_t * ui_LabelBoton;
void ui_event_DropdownOpciones(lv_event_t * e);
lv_obj_t * ui_DropdownOpciones;
void ui_event_ButtonVolverConfiguracionAvanzada(lv_event_t * e);
lv_obj_t * ui_ButtonVolverConfiguracionAvanzada;
lv_obj_t * ui_LabelVolverConfiguracionUsuario2;
lv_obj_t * ui_LabelNombreSpinbox1;
lv_obj_t * ui_LabelNombreSpinbox2;
void ui_event_KeyboardCodigo(lv_event_t * e);
lv_obj_t * ui_KeyboardCodigo;
lv_obj_t * ui_Panel2;
lv_obj_t * ui_TextAreaCodigo;
void ui_event_ButtonIngresoConfigsAvanzadas(lv_event_t * e);
lv_obj_t * ui_ButtonIngresoConfigsAvanzadas;
lv_obj_t * ui_LabelVolverConfiguracionUsuario4;

// SCREEN: ui_Diagnostico
void ui_Diagnostico_screen_init(void);
lv_obj_t * ui_Diagnostico;
void ui_event_ButtonVolverDiagnostico(lv_event_t * e);
lv_obj_t * ui_ButtonVolverDiagnostico;
lv_obj_t * ui_LabelVolverConfiguracionUsuario3;
void ui_event_BotonEtapa5(lv_event_t * e);
lv_obj_t * ui_BotonEtapa5;
lv_obj_t * ui_Label23;
void ui_event_BotonEtapa6(lv_event_t * e);
lv_obj_t * ui_BotonEtapa6;
lv_obj_t * ui_Label22;
void ui_event_BotonEtapa1(lv_event_t * e);
lv_obj_t * ui_BotonEtapa1;
lv_obj_t * ui_Label11;
void ui_event_BotonEtapa4(lv_event_t * e);
lv_obj_t * ui_BotonEtapa4;
lv_obj_t * ui_Label14;
void ui_event_BotonEtapa3(lv_event_t * e);
lv_obj_t * ui_BotonEtapa3;
lv_obj_t * ui_Label21;
void ui_event_BotonEtapa2(lv_event_t * e);
lv_obj_t * ui_BotonEtapa2;
lv_obj_t * ui_Label20;
void ui_event_ButtonPurga(lv_event_t * e);
lv_obj_t * ui_ButtonPurga;
lv_obj_t * ui_Label6;
lv_obj_t * ui_Label1;
void ui_event_CheckboxDiagnostico(lv_event_t * e);
lv_obj_t * ui_CheckboxDiagnostico;
lv_obj_t * ui____initial_actions0;
const lv_image_dsc_t * ui_imgset_logo_flowing_300x[1] = {&ui_img_logo_flowing_300x80_png};
const lv_image_dsc_t * ui_imgset_logo_flowing_blanco[1] = {&ui_img_logo_flowing_blanco90_png};

///////////////////// TEST LVGL SETTINGS ////////////////////
#if LV_COLOR_DEPTH != 16
    #error "LV_COLOR_DEPTH should be 16bit to match SquareLine Studio's settings"
#endif

///////////////////// ANIMATIONS ////////////////////

///////////////////// FUNCTIONS ////////////////////
void ui_event_ButtonEncendidoGrande(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        CambiarEstadoCaldera(e);
        _ui_screen_change(&ui_Principal, LV_SCR_LOAD_ANIM_NONE, 0, 0, &ui_Principal_screen_init);
    }
}
void ui_event_ButtonAlarma2(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Alertas, LV_SCR_LOAD_ANIM_NONE, 0, 0, &ui_Alertas_screen_init);
    }
}
void ui_event_ButtonReset(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        restartESP32(e);
    }
}
void ui_event_Principal(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_SCREEN_LOADED) {
        cargarValoresSP(e);
    }
}
void ui_event_PanelConfiguraciones(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_ConfiguracionesUsuario, LV_SCR_LOAD_ANIM_NONE, 0, 0, &ui_ConfiguracionesUsuario_screen_init);
    }
}
void ui_event_ButtonAlarma(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Alertas, LV_SCR_LOAD_ANIM_NONE, 0, 0, &ui_Alertas_screen_init);
    }
}
void ui_event_ButtonEncendido(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        CambiarEstadoCaldera(e);
        _ui_screen_change(&ui_Apagado, LV_SCR_LOAD_ANIM_NONE, 0, 0, &ui_Apagado_screen_init);
    }
    if(event_code == LV_EVENT_LONG_PRESSED) {
        restartESP32(e);
    }
}
void ui_event_PanelAlarmas(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Alarmas, LV_SCR_LOAD_ANIM_NONE, 0, 0, &ui_Alarmas_screen_init);
    }
}
void ui_event_Alarmas(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_active()) == LV_DIR_BOTTOM) {
        lv_indev_wait_release(lv_indev_active());
        _ui_screen_change(&ui_ConfiguracionesUsuario, LV_SCR_LOAD_ANIM_NONE, 0, 0, &ui_ConfiguracionesUsuario_screen_init);
    }
    if(event_code == LV_EVENT_SCREEN_LOADED) {
        cargarValoresAlarmas(e);
    }
}
void ui_event_ButtonVolverAlarmas(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Principal, LV_SCR_LOAD_ANIM_NONE, 0, 0, &ui_Principal_screen_init);
    }
}
void ui_event_ImageLogoConfigsUsuario2(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_ConfiguracionesAvanzadas, LV_SCR_LOAD_ANIM_NONE, 0, 0, &ui_ConfiguracionesAvanzadas_screen_init);
        cargarValoresCodigoIngreso(e);
    }
}
void ui_event_Button1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        borrarAlarmas(e);
        cargarValoresAlarmas(e);
    }
}
void ui_event_ButtonVovler2(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        volverDeAlerta(e);
    }
}
void ui_event_ConfiguracionesUsuario(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_SCREEN_LOADED) {
        cargarValoresConfigUsuario(e);
    }
}
void ui_event_CalefacionMas(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_spinbox_step(ui_SpinboxCalefaccion, 1);
    }
    if(event_code == LV_EVENT_LONG_PRESSED_REPEAT) {
        _ui_spinbox_step(ui_SpinboxCalefaccion, 1);
    }
}
void ui_event_CalefaccionMenos(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_spinbox_step(ui_SpinboxCalefaccion, -1);
    }
    if(event_code == LV_EVENT_LONG_PRESSED_REPEAT) {
        _ui_spinbox_step(ui_SpinboxCalefaccion, -1);
    }
}
void ui_event_SpinboxCalefaccion(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_VALUE_CHANGED) {
        cambiarConfigTempCalefaccion(e);
    }
}
void ui_event_ACSMas(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_spinbox_step(ui_SpinboxACS, 1);
    }
    if(event_code == LV_EVENT_LONG_PRESSED_REPEAT) {
        _ui_spinbox_step(ui_SpinboxACS, 1);
    }
}
void ui_event_ACSMenos(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_spinbox_step(ui_SpinboxACS, -1);
    }
    if(event_code == LV_EVENT_LONG_PRESSED_REPEAT) {
        _ui_spinbox_step(ui_SpinboxACS, -1);
    }
}
void ui_event_SpinboxACS(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_VALUE_CHANGED) {
        cambiarConfigTempACS(e);
    }
}
void ui_event_ButtonVolverConfiguracionUsuario(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Principal, LV_SCR_LOAD_ANIM_NONE, 0, 0, &ui_Principal_screen_init);
    }
}
void ui_event_ButtonCalefaccion(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        camibarEstadoCalefaccion(e);
    }
}
void ui_event_ImageLogoConfigsUsuario(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_ConfiguracionesAvanzadas, LV_SCR_LOAD_ANIM_NONE, 0, 0, &ui_ConfiguracionesAvanzadas_screen_init);
        cargarValoresCodigoIngreso(e);
    }
}
void ui_event_ConfiguracionesAvanzadas(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_SCREEN_LOADED) {
        SeleccionConfiguracionesAvanzadas(e);
    }
}
void ui_event_botonMasSpinbox1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_spinbox_step(ui_Spinbox1, 1);
    }
    if(event_code == LV_EVENT_LONG_PRESSED_REPEAT) {
        _ui_spinbox_step(ui_Spinbox1, 1);
    }
}
void ui_event_botonMenosSpinbox1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_spinbox_step(ui_Spinbox1, -1);
    }
    if(event_code == LV_EVENT_LONG_PRESSED_REPEAT) {
        _ui_spinbox_step(ui_Spinbox1, -1);
    }
}
void ui_event_Spinbox1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_VALUE_CHANGED) {
        cambiarConfigSpinbox1(e);
    }
}
void ui_event_botonMasSpinbox2(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_spinbox_step(ui_Spinbox2, 1);
    }
    if(event_code == LV_EVENT_LONG_PRESSED_REPEAT) {
        _ui_spinbox_step(ui_Spinbox2, 1);
    }
}
void ui_event_botonMenosSpinbox2(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_spinbox_step(ui_Spinbox2, -1);
    }
    if(event_code == LV_EVENT_LONG_PRESSED_REPEAT) {
        _ui_spinbox_step(ui_Spinbox2, -1);
    }
}
void ui_event_Spinbox2(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_VALUE_CHANGED) {
        cambiarConfigSpinbox2(e);
    }
}
void ui_event_ButtonCambioDerecha(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Diagnostico, LV_SCR_LOAD_ANIM_NONE, 0, 0, &ui_Diagnostico_screen_init);
    }
}
void ui_event_DropdownOpciones(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_VALUE_CHANGED) {
        SeleccionConfiguracionesAvanzadas(e);
    }
}
void ui_event_ButtonVolverConfiguracionAvanzada(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Principal, LV_SCR_LOAD_ANIM_NONE, 0, 0, &ui_Principal_screen_init);
    }
}
void ui_event_KeyboardCodigo(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_READY) {
        verificarCodigo(e);
    }
}
void ui_event_ButtonIngresoConfigsAvanzadas(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_ConfiguracionesUsuario, LV_SCR_LOAD_ANIM_NONE, 0, 0, &ui_ConfiguracionesUsuario_screen_init);
    }
}
void ui_event_ButtonVolverDiagnostico(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_ConfiguracionesAvanzadas, LV_SCR_LOAD_ANIM_NONE, 0, 0, &ui_ConfiguracionesAvanzadas_screen_init);
    }
}
void ui_event_BotonEtapa5(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        pruebaSalidas(e);
    }
}
void ui_event_BotonEtapa6(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        pruebaSalidas(e);
    }
}
void ui_event_BotonEtapa1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        pruebaSalidas(e);
    }
}
void ui_event_BotonEtapa4(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        pruebaSalidas(e);
    }
}
void ui_event_BotonEtapa3(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        pruebaSalidas(e);
    }
}
void ui_event_BotonEtapa2(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        pruebaSalidas(e);
    }
}
void ui_event_ButtonPurga(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        purga(e);
    }
}
void ui_event_CheckboxDiagnostico(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_VALUE_CHANGED) {
        cambiarEstadoDiagnostico(e);
    }
}

///////////////////// SCREENS ////////////////////

void ui_init(void)
{
    lv_disp_t * dispp = lv_display_get_default();
    lv_theme_t * theme = lv_theme_default_init(dispp, lv_palette_main(LV_PALETTE_BLUE), lv_palette_main(LV_PALETTE_RED),
                                               false, LV_FONT_DEFAULT);
    lv_disp_set_theme(dispp, theme);
    ui_Inicio_screen_init();
    ui_Apagado_screen_init();
    ui_Principal_screen_init();
    ui_Alarmas_screen_init();
    ui_Alertas_screen_init();
    ui_ConfiguracionesUsuario_screen_init();
    ui_ConfiguracionesAvanzadas_screen_init();
    ui_Diagnostico_screen_init();
    ui____initial_actions0 = lv_obj_create(NULL);
    lv_disp_load_scr(ui_Inicio);
    estadoControlUI_ = obtenerEstadoControl();
}
