// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 9.1.0
// Project name: SquareLine_Project2

#ifndef _SQUARELINE_PROJECT2_UI_H
#define _SQUARELINE_PROJECT2_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#if defined __has_include
#if __has_include("lvgl.h")
#include "lvgl.h"
#elif __has_include("lvgl/lvgl.h")
#include "lvgl/lvgl.h"
#else
#include "lvgl.h"
#endif
#else
#include "lvgl.h"
#endif

#include "G:\Mi unidad\FLOWING\FLOWCORE V4\FlowCore-V4.0\modules\NVS\NVS.h"
#include "G:\Mi unidad\FLOWING\FLOWCORE V4\FlowCore-V4.0\modules\controles\controles.h"

#include "ui_helpers.h"
#include "ui_events.h"

extern const struct Configs *configuracionesUI_;
extern const int32_t *alarmasUI_; 
extern const estadoControl_t* estadoControlUI_; 

// SCREEN: ui_Inicio
void ui_Inicio_screen_init(void);
extern lv_obj_t * ui_Inicio;
extern lv_obj_t * ui_LogoInicio;
extern lv_obj_t * ui_LabelInicio;
// SCREEN: ui_Apagado
void ui_Apagado_screen_init(void);
extern lv_obj_t * ui_Apagado;
void ui_event_ButtonEncendidoGrande(lv_event_t * e);
extern lv_obj_t * ui_ButtonEncendidoGrande;
extern lv_obj_t * ui_LabelSimboloPower2;
void ui_event_ButtonAlarma2(lv_event_t * e);
extern lv_obj_t * ui_ButtonAlarma2;
extern lv_obj_t * ui_LabelSimboloAlarma2;
void ui_event_ButtonReset(lv_event_t * e);
extern lv_obj_t * ui_ButtonReset;
extern lv_obj_t * ui_LabelSimboloReset;
extern lv_obj_t * ui_ImageLogoFlowing3;
// SCREEN: ui_Principal
void ui_Principal_screen_init(void);
void ui_event_Principal(lv_event_t * e);
extern lv_obj_t * ui_Principal;
void ui_event_PanelConfiguraciones(lv_event_t * e);
extern lv_obj_t * ui_PanelConfiguraciones;
extern lv_obj_t * ui_LabelSPAcs;
extern lv_obj_t * ui_LabelSPCal;
extern lv_obj_t * ui_LabelTempSPAcs;
extern lv_obj_t * ui_LabelTempSPCal;
extern lv_obj_t * ui_LabelSimboloConfiguracion;
extern lv_obj_t * ui_PanelValores;
extern lv_obj_t * ui_ArcTemperatura;
extern lv_obj_t * ui_LabelTemperatura;
extern lv_obj_t * ui_LabelPresion;
extern lv_obj_t * ui_ImageCal;
extern lv_obj_t * ui_ImageAcs;
void ui_event_ButtonAlarma(lv_event_t * e);
extern lv_obj_t * ui_ButtonAlarma;
extern lv_obj_t * ui_LabelSimboloAlarma;
void ui_event_ButtonEncendido(lv_event_t * e);
extern lv_obj_t * ui_ButtonEncendido;
extern lv_obj_t * ui_LabelSimboloPower;
extern lv_obj_t * ui_ImageLogoFlowing;
void ui_event_PanelAlarmas(lv_event_t * e);
extern lv_obj_t * ui_PanelAlarmas;
extern lv_obj_t * ui_LabelAlarma;
extern lv_obj_t * ui_LabelDiagnosticoPrincipal;
// SCREEN: ui_Alarmas
void ui_Alarmas_screen_init(void);
void ui_event_Alarmas(lv_event_t * e);
extern lv_obj_t * ui_Alarmas;
extern lv_obj_t * ui_Label16;
extern lv_obj_t * ui_Alarma1;
extern lv_obj_t * ui_Alarma2;
extern lv_obj_t * ui_Alarma3;
extern lv_obj_t * ui_Alarma4;
extern lv_obj_t * ui_Alarma5;
extern lv_obj_t * ui_SinAlarma;
void ui_event_ButtonVolverAlarmas(lv_event_t * e);
extern lv_obj_t * ui_ButtonVolverAlarmas;
extern lv_obj_t * ui_LabelVolverAlarmas;
void ui_event_ImageLogoConfigsUsuario2(lv_event_t * e);
extern lv_obj_t * ui_ImageLogoConfigsUsuario2;
void ui_event_Button1(lv_event_t * e);
extern lv_obj_t * ui_Button1;
extern lv_obj_t * ui_Label2;
// SCREEN: ui_Alertas
void ui_Alertas_screen_init(void);
extern lv_obj_t * ui_Alertas;
extern lv_obj_t * ui_Panel4;
extern lv_obj_t * ui_LabelError;
extern lv_obj_t * ui_LabelAclaracion;
void ui_event_ButtonVovler2(lv_event_t * e);
extern lv_obj_t * ui_ButtonVovler2;
extern lv_obj_t * ui_Label12;
extern lv_obj_t * ui_ImageLogoFlowing2;
// SCREEN: ui_ConfiguracionesUsuario
void ui_ConfiguracionesUsuario_screen_init(void);
void ui_event_ConfiguracionesUsuario(lv_event_t * e);
extern lv_obj_t * ui_ConfiguracionesUsuario;
extern lv_obj_t * ui_Container1;
void ui_event_CalefacionMas(lv_event_t * e);
extern lv_obj_t * ui_CalefacionMas;
extern lv_obj_t * ui_Label4;
void ui_event_CalefaccionMenos(lv_event_t * e);
extern lv_obj_t * ui_CalefaccionMenos;
extern lv_obj_t * ui_Label5;
void ui_event_SpinboxCalefaccion(lv_event_t * e);
extern lv_obj_t * ui_SpinboxCalefaccion;
extern lv_obj_t * ui_Container2;
void ui_event_ACSMas(lv_event_t * e);
extern lv_obj_t * ui_ACSMas;
extern lv_obj_t * ui_Label19;
void ui_event_ACSMenos(lv_event_t * e);
extern lv_obj_t * ui_ACSMenos;
extern lv_obj_t * ui_Label13;
void ui_event_SpinboxACS(lv_event_t * e);
extern lv_obj_t * ui_SpinboxACS;
extern lv_obj_t * ui_ImageConfigAcs;
void ui_event_ButtonVolverConfiguracionUsuario(lv_event_t * e);
extern lv_obj_t * ui_ButtonVolverConfiguracionUsuario;
extern lv_obj_t * ui_LabelVolverConfiguracionUsuario;
void ui_event_ButtonCalefaccion(lv_event_t * e);
extern lv_obj_t * ui_ButtonCalefaccion;
extern lv_obj_t * ui_ImageConfigCalefaccion;
void ui_event_ImageLogoConfigsUsuario(lv_event_t * e);
extern lv_obj_t * ui_ImageLogoConfigsUsuario;
extern lv_obj_t * ui_LabelTituloConfigsUsuario;
// SCREEN: ui_ConfiguracionesAvanzadas
void ui_ConfiguracionesAvanzadas_screen_init(void);
void ui_event_ConfiguracionesAvanzadas(lv_event_t * e);
extern lv_obj_t * ui_ConfiguracionesAvanzadas;
extern lv_obj_t * ui_ContainerSpinbox1;
void ui_event_botonMasSpinbox1(lv_event_t * e);
extern lv_obj_t * ui_botonMasSpinbox1;
extern lv_obj_t * ui_LabelMasSpinbox1;
void ui_event_botonMenosSpinbox1(lv_event_t * e);
extern lv_obj_t * ui_botonMenosSpinbox1;
extern lv_obj_t * ui_LabelMenosSpinbox1;
void ui_event_Spinbox1(lv_event_t * e);
extern lv_obj_t * ui_Spinbox1;
extern lv_obj_t * ui_ContainerSpinbox2;
void ui_event_botonMasSpinbox2(lv_event_t * e);
extern lv_obj_t * ui_botonMasSpinbox2;
extern lv_obj_t * ui_LabelMasSpinbox2;
void ui_event_botonMenosSpinbox2(lv_event_t * e);
extern lv_obj_t * ui_botonMenosSpinbox2;
extern lv_obj_t * ui_LabelMenosSpinbox2;
void ui_event_Spinbox2(lv_event_t * e);
extern lv_obj_t * ui_Spinbox2;
void ui_event_ButtonCambioDerecha(lv_event_t * e);
extern lv_obj_t * ui_ButtonCambioDerecha;
extern lv_obj_t * ui_LabelBoton;
void ui_event_DropdownOpciones(lv_event_t * e);
extern lv_obj_t * ui_DropdownOpciones;
void ui_event_ButtonVolverConfiguracionAvanzada(lv_event_t * e);
extern lv_obj_t * ui_ButtonVolverConfiguracionAvanzada;
extern lv_obj_t * ui_LabelVolverConfiguracionUsuario2;
extern lv_obj_t * ui_LabelNombreSpinbox1;
extern lv_obj_t * ui_LabelNombreSpinbox2;
void ui_event_KeyboardCodigo(lv_event_t * e);
extern lv_obj_t * ui_KeyboardCodigo;
extern lv_obj_t * ui_Panel2;
extern lv_obj_t * ui_TextAreaCodigo;
void ui_event_ButtonIngresoConfigsAvanzadas(lv_event_t * e);
extern lv_obj_t * ui_ButtonIngresoConfigsAvanzadas;
extern lv_obj_t * ui_LabelVolverConfiguracionUsuario4;
// SCREEN: ui_Diagnostico
void ui_Diagnostico_screen_init(void);
extern lv_obj_t * ui_Diagnostico;
void ui_event_ButtonVolverDiagnostico(lv_event_t * e);
extern lv_obj_t * ui_ButtonVolverDiagnostico;
extern lv_obj_t * ui_LabelVolverConfiguracionUsuario3;
void ui_event_BotonEtapa5(lv_event_t * e);
extern lv_obj_t * ui_BotonEtapa5;
extern lv_obj_t * ui_Label23;
void ui_event_BotonEtapa6(lv_event_t * e);
extern lv_obj_t * ui_BotonEtapa6;
extern lv_obj_t * ui_Label22;
void ui_event_BotonEtapa1(lv_event_t * e);
extern lv_obj_t * ui_BotonEtapa1;
extern lv_obj_t * ui_Label11;
void ui_event_BotonEtapa4(lv_event_t * e);
extern lv_obj_t * ui_BotonEtapa4;
extern lv_obj_t * ui_Label14;
void ui_event_BotonEtapa3(lv_event_t * e);
extern lv_obj_t * ui_BotonEtapa3;
extern lv_obj_t * ui_Label21;
void ui_event_BotonEtapa2(lv_event_t * e);
extern lv_obj_t * ui_BotonEtapa2;
extern lv_obj_t * ui_Label20;
void ui_event_ButtonPurga(lv_event_t * e);
extern lv_obj_t * ui_ButtonPurga;
extern lv_obj_t * ui_Label6;
extern lv_obj_t * ui_Label1;
void ui_event_CheckboxDiagnostico(lv_event_t * e);
extern lv_obj_t * ui_CheckboxDiagnostico;
extern lv_obj_t * ui____initial_actions0;


LV_IMG_DECLARE(ui_img_logo_flowing_300x80_png);    // assets/Logo Flowing 300x80.png
LV_IMG_DECLARE(ui_img_logo_flowing_blanco90_png);    // assets/Logo Flowing blanco90.png
LV_IMG_DECLARE(ui_img_icono_calefaccion_apagada_png);    // assets/icono_calefaccion_apagada.png
LV_IMG_DECLARE(ui_img_icono_acs_apagada_png);    // assets/icono_acs_apagada.png
LV_IMG_DECLARE(ui_img_icono_acs_encendida_png);    // assets/icono_acs_encendida.png
LV_IMG_DECLARE(ui_img_icono_calefaccion_encendida_png);    // assets/icono_calefaccion_encendida.png






void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
