// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 9.1.0
// Project name: SquareLine_Project2

#include "ui.h"

void ui_Alarmas_screen_init(void)
{
    ui_Alarmas = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_Alarmas, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Alarmas, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Alarmas, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label16 = lv_label_create(ui_Alarmas);
    lv_obj_set_width(ui_Label16, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label16, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label16, -25);
    lv_obj_set_y(ui_Label16, -110);
    lv_obj_set_align(ui_Label16, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label16, "HISTORIAL DE ALARMAS");
    lv_obj_set_style_text_color(ui_Label16, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label16, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label16, &lv_font_montserrat_30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Alarma1 = lv_label_create(ui_Alarmas);
    lv_obj_set_width(ui_Alarma1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Alarma1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Alarma1, 75);
    lv_obj_set_y(ui_Alarma1, -50);
    lv_obj_set_align(ui_Alarma1, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_Alarma1, "1.");
    lv_obj_add_flag(ui_Alarma1, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_set_style_text_color(ui_Alarma1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Alarma1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_Alarma1, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Alarma1, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Alarma2 = lv_label_create(ui_Alarmas);
    lv_obj_set_width(ui_Alarma2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Alarma2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Alarma2, 75);
    lv_obj_set_y(ui_Alarma2, -10);
    lv_obj_set_align(ui_Alarma2, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_Alarma2, "2.");
    lv_obj_add_flag(ui_Alarma2, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_set_style_text_color(ui_Alarma2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Alarma2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_Alarma2, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Alarma2, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Alarma3 = lv_label_create(ui_Alarmas);
    lv_obj_set_width(ui_Alarma3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Alarma3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Alarma3, 75);
    lv_obj_set_y(ui_Alarma3, 30);
    lv_obj_set_align(ui_Alarma3, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_Alarma3, "3.");
    lv_obj_add_flag(ui_Alarma3, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_set_style_text_color(ui_Alarma3, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Alarma3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_Alarma3, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Alarma3, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Alarma4 = lv_label_create(ui_Alarmas);
    lv_obj_set_width(ui_Alarma4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Alarma4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Alarma4, 75);
    lv_obj_set_y(ui_Alarma4, 70);
    lv_obj_set_align(ui_Alarma4, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_Alarma4, "4.");
    lv_obj_add_flag(ui_Alarma4, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_set_style_text_color(ui_Alarma4, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Alarma4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_Alarma4, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Alarma4, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Alarma5 = lv_label_create(ui_Alarmas);
    lv_obj_set_width(ui_Alarma5, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Alarma5, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Alarma5, 75);
    lv_obj_set_y(ui_Alarma5, 110);
    lv_obj_set_align(ui_Alarma5, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_Alarma5, "5.");
    lv_obj_add_flag(ui_Alarma5, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_set_style_text_color(ui_Alarma5, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Alarma5, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_Alarma5, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Alarma5, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SinAlarma = lv_label_create(ui_Alarmas);
    lv_obj_set_width(ui_SinAlarma, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_SinAlarma, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_SinAlarma, 25);
    lv_obj_set_y(ui_SinAlarma, 0);
    lv_obj_set_align(ui_SinAlarma, LV_ALIGN_CENTER);
    lv_label_set_text(ui_SinAlarma, "NO HAY ALARMAS REGISTRADAS");
    lv_obj_set_style_text_color(ui_SinAlarma, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_SinAlarma, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_SinAlarma, &lv_font_montserrat_22, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ButtonVolverAlarmas = lv_button_create(ui_Alarmas);
    lv_obj_set_width(ui_ButtonVolverAlarmas, 65);
    lv_obj_set_height(ui_ButtonVolverAlarmas, 100);
    lv_obj_set_x(ui_ButtonVolverAlarmas, -213);
    lv_obj_set_y(ui_ButtonVolverAlarmas, 0);
    lv_obj_set_align(ui_ButtonVolverAlarmas, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ButtonVolverAlarmas, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_ButtonVolverAlarmas, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_ButtonVolverAlarmas, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_ButtonVolverAlarmas, lv_color_hex(0x39009C), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ButtonVolverAlarmas, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelVolverAlarmas = lv_label_create(ui_ButtonVolverAlarmas);
    lv_obj_set_width(ui_LabelVolverAlarmas, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelVolverAlarmas, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_LabelVolverAlarmas, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelVolverAlarmas, LV_SYMBOL_PREV);
    lv_obj_set_style_text_font(ui_LabelVolverAlarmas, &lv_font_montserrat_30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ImageLogoConfigsUsuario2 = lv_image_create(ui_Alarmas);
    lv_image_set_src(ui_ImageLogoConfigsUsuario2, &ui_img_logo_flowing_blanco90_png);
    lv_obj_set_width(ui_ImageLogoConfigsUsuario2, 150);
    lv_obj_set_height(ui_ImageLogoConfigsUsuario2, 40);
    lv_obj_set_x(ui_ImageLogoConfigsUsuario2, -162);
    lv_obj_set_y(ui_ImageLogoConfigsUsuario2, 137);
    lv_obj_set_align(ui_ImageLogoConfigsUsuario2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ImageLogoConfigsUsuario2, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_ImageLogoConfigsUsuario2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_image_set_scale(ui_ImageLogoConfigsUsuario2, 100);

    ui_Button1 = lv_button_create(ui_Alarmas);
    lv_obj_set_width(ui_Button1, 50);
    lv_obj_set_height(ui_Button1, 50);
    lv_obj_set_x(ui_Button1, 198);
    lv_obj_set_y(ui_Button1, -112);
    lv_obj_set_align(ui_Button1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button1, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_Button1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Button1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Button1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label2 = lv_label_create(ui_Button1);
    lv_obj_set_width(ui_Label2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label2, LV_SYMBOL_TRASH);
    lv_obj_set_style_text_color(ui_Label2, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label2, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_ButtonVolverAlarmas, ui_event_ButtonVolverAlarmas, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_ImageLogoConfigsUsuario2, ui_event_ImageLogoConfigsUsuario2, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Button1, ui_event_Button1, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Alarmas, ui_event_Alarmas, LV_EVENT_ALL, NULL);

}
