// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 9.1.0
// Project name: SquareLine_Project2

#include "ui.h"

void ui_Apagado_screen_init(void)
{
    ui_Apagado = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_Apagado, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Apagado, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Apagado, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ButtonEncendidoGrande = lv_button_create(ui_Apagado);
    lv_obj_set_width(ui_ButtonEncendidoGrande, 200);
    lv_obj_set_height(ui_ButtonEncendidoGrande, 200);
    lv_obj_set_align(ui_ButtonEncendidoGrande, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ButtonEncendidoGrande, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_ButtonEncendidoGrande,
                       LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE |
                       LV_OBJ_FLAG_SCROLLABLE);     /// Flags
    lv_obj_set_style_radius(ui_ButtonEncendidoGrande, 100, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_ButtonEncendidoGrande, lv_color_hex(0xB42020), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ButtonEncendidoGrande, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_ButtonEncendidoGrande, lv_color_hex(0x808080), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_ButtonEncendidoGrande, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_ButtonEncendidoGrande, 5, LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_radius(ui_ButtonEncendidoGrande, 100, LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_bg_color(ui_ButtonEncendidoGrande, lv_color_hex(0x39009C), LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_bg_opa(ui_ButtonEncendidoGrande, 255, LV_PART_MAIN | LV_STATE_PRESSED);

    ui_LabelSimboloPower2 = lv_label_create(ui_ButtonEncendidoGrande);
    lv_obj_set_width(ui_LabelSimboloPower2, 50);
    lv_obj_set_height(ui_LabelSimboloPower2, 50);
    lv_obj_set_x(ui_LabelSimboloPower2, -25);
    lv_obj_set_y(ui_LabelSimboloPower2, -25);
    lv_obj_set_align(ui_LabelSimboloPower2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelSimboloPower2, LV_SYMBOL_POWER);
    lv_obj_set_style_text_color(ui_LabelSimboloPower2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelSimboloPower2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_LabelSimboloPower2, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelSimboloPower2, &lv_font_montserrat_48, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_transform_scale(ui_LabelSimboloPower2, 512, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ButtonAlarma2 = lv_button_create(ui_Apagado);
    lv_obj_set_width(ui_ButtonAlarma2, 50);
    lv_obj_set_height(ui_ButtonAlarma2, 50);
    lv_obj_set_x(ui_ButtonAlarma2, 165);
    lv_obj_set_y(ui_ButtonAlarma2, -95);
    lv_obj_set_align(ui_ButtonAlarma2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ButtonAlarma2, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_ButtonAlarma2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_ButtonAlarma2, lv_color_hex(0xC52222), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ButtonAlarma2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelSimboloAlarma2 = lv_label_create(ui_ButtonAlarma2);
    lv_obj_set_width(ui_LabelSimboloAlarma2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelSimboloAlarma2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_LabelSimboloAlarma2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelSimboloAlarma2, LV_SYMBOL_WARNING);
    lv_obj_set_style_text_color(ui_LabelSimboloAlarma2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelSimboloAlarma2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelSimboloAlarma2, &lv_font_montserrat_30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ButtonReset = lv_button_create(ui_Apagado);
    lv_obj_set_width(ui_ButtonReset, 50);
    lv_obj_set_height(ui_ButtonReset, 50);
    lv_obj_set_x(ui_ButtonReset, -165);
    lv_obj_set_y(ui_ButtonReset, -95);
    lv_obj_set_align(ui_ButtonReset, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ButtonReset, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_ButtonReset, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_ButtonReset, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ButtonReset, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelSimboloReset = lv_label_create(ui_ButtonReset);
    lv_obj_set_width(ui_LabelSimboloReset, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelSimboloReset, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_LabelSimboloReset, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelSimboloReset, LV_SYMBOL_REFRESH);
    lv_obj_set_style_text_color(ui_LabelSimboloReset, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelSimboloReset, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelSimboloReset, &lv_font_montserrat_30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ImageLogoFlowing3 = lv_image_create(ui_Apagado);
    lv_image_set_src(ui_ImageLogoFlowing3, &ui_img_logo_flowing_blanco90_png);
    lv_obj_set_width(ui_ImageLogoFlowing3, 150);
    lv_obj_set_height(ui_ImageLogoFlowing3, 40);
    lv_obj_set_x(ui_ImageLogoFlowing3, -162);
    lv_obj_set_y(ui_ImageLogoFlowing3, 137);
    lv_obj_set_align(ui_ImageLogoFlowing3, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_ImageLogoFlowing3,
                       LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE |
                       LV_OBJ_FLAG_SCROLLABLE);     /// Flags
    lv_image_set_scale(ui_ImageLogoFlowing3, 100);

    lv_obj_add_event_cb(ui_ButtonEncendidoGrande, ui_event_ButtonEncendidoGrande, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_ButtonAlarma2, ui_event_ButtonAlarma2, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_ButtonReset, ui_event_ButtonReset, LV_EVENT_ALL, NULL);

}
