// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 9.1.0
// Project name: SquareLine_Project2

#include "ui.h"

void ui_Alertas_screen_init(void)
{
    ui_Alertas = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_Alertas, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Alertas, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Alertas, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel4 = lv_obj_create(ui_Alertas);
    lv_obj_set_width(ui_Panel4, 450);
    lv_obj_set_height(ui_Panel4, 229);
    lv_obj_set_x(ui_Panel4, 0);
    lv_obj_set_y(ui_Panel4, -30);
    lv_obj_set_align(ui_Panel4, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_Panel4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Panel4, lv_color_hex(0xC52222), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel4, 80, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelError = lv_label_create(ui_Panel4);
    lv_obj_set_width(ui_LabelError, 400);
    lv_obj_set_height(ui_LabelError, 86);
    lv_obj_set_x(ui_LabelError, 0);
    lv_obj_set_y(ui_LabelError, -50);
    lv_obj_set_align(ui_LabelError, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelError, "ERROR");
    lv_obj_set_style_text_color(ui_LabelError, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelError, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_LabelError, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelError, &lv_font_montserrat_34, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelAclaracion = lv_label_create(ui_Panel4);
    lv_obj_set_width(ui_LabelAclaracion, 400);
    lv_obj_set_height(ui_LabelAclaracion, 100);
    lv_obj_set_x(ui_LabelAclaracion, 0);
    lv_obj_set_y(ui_LabelAclaracion, 50);
    lv_obj_set_align(ui_LabelAclaracion, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelAclaracion, "ACLARACION");
    lv_obj_set_style_text_color(ui_LabelAclaracion, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelAclaracion, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_LabelAclaracion, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelAclaracion, &lv_font_montserrat_26, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ButtonVovler2 = lv_button_create(ui_Alertas);
    lv_obj_set_width(ui_ButtonVovler2, 144);
    lv_obj_set_height(ui_ButtonVovler2, 50);
    lv_obj_set_x(ui_ButtonVovler2, 0);
    lv_obj_set_y(ui_ButtonVovler2, 120);
    lv_obj_set_align(ui_ButtonVovler2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ButtonVovler2, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_ButtonVovler2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_ButtonVovler2, lv_color_hex(0x39009C), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ButtonVovler2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label12 = lv_label_create(ui_ButtonVovler2);
    lv_obj_set_width(ui_Label12, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label12, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label12, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label12, "Inicio");
    lv_obj_set_style_text_color(ui_Label12, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label12, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label12, &lv_font_montserrat_28, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_ButtonVovler2, ui_event_ButtonVovler2, LV_EVENT_ALL, NULL);

}
