// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 9.1.0
// Project name: SquareLine_Project2

#include "ui.h"

void ui_ConfiguracionesUsuario_screen_init(void)
{
    ui_ConfiguracionesUsuario = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_ConfiguracionesUsuario, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_ConfiguracionesUsuario, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ConfiguracionesUsuario, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Container1 = lv_obj_create(ui_ConfiguracionesUsuario);
    lv_obj_remove_style_all(ui_Container1);
    lv_obj_set_width(ui_Container1, 307);
    lv_obj_set_height(ui_Container1, 92);
    lv_obj_set_x(ui_Container1, -20);
    lv_obj_set_y(ui_Container1, -40);
    lv_obj_set_align(ui_Container1, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_Container1, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_CalefacionMas = lv_button_create(ui_Container1);
    lv_obj_set_width(ui_CalefacionMas, 75);
    lv_obj_set_height(ui_CalefacionMas, 65);
    lv_obj_set_x(ui_CalefacionMas, -105);
    lv_obj_set_y(ui_CalefacionMas, 0);
    lv_obj_set_align(ui_CalefacionMas, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_CalefacionMas, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_CalefacionMas, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_CalefacionMas, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_CalefacionMas, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_CalefacionMas, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_CalefacionMas, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label4 = lv_label_create(ui_CalefacionMas);
    lv_obj_set_width(ui_Label4, 30);
    lv_obj_set_height(ui_Label4, 39);
    lv_obj_set_align(ui_Label4, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label4, LV_SYMBOL_PLUS);
    lv_obj_set_style_text_color(ui_Label4, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_Label4, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label4, &lv_font_montserrat_30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_CalefaccionMenos = lv_button_create(ui_Container1);
    lv_obj_set_width(ui_CalefaccionMenos, 75);
    lv_obj_set_height(ui_CalefaccionMenos, 65);
    lv_obj_set_x(ui_CalefaccionMenos, 105);
    lv_obj_set_y(ui_CalefaccionMenos, 0);
    lv_obj_set_align(ui_CalefaccionMenos, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_CalefaccionMenos, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_CalefaccionMenos, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_CalefaccionMenos, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_CalefaccionMenos, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_CalefaccionMenos, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_CalefaccionMenos, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label5 = lv_label_create(ui_CalefaccionMenos);
    lv_obj_set_width(ui_Label5, 30);
    lv_obj_set_height(ui_Label5, 39);
    lv_obj_set_align(ui_Label5, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label5, LV_SYMBOL_MINUS);
    lv_obj_set_style_text_color(ui_Label5, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label5, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_Label5, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label5, &lv_font_montserrat_30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SpinboxCalefaccion = lv_spinbox_create(ui_Container1);
    lv_obj_set_width(ui_SpinboxCalefaccion, 150);
    lv_obj_set_height(ui_SpinboxCalefaccion, 80);
    lv_obj_set_align(ui_SpinboxCalefaccion, LV_ALIGN_CENTER);
    lv_spinbox_set_digit_format(ui_SpinboxCalefaccion, 3, 2);
    lv_spinbox_set_range(ui_SpinboxCalefaccion, 0, 999);
    lv_spinbox_set_cursor_pos(ui_SpinboxCalefaccion, 1 - 1);
    lv_obj_set_style_text_color(ui_SpinboxCalefaccion, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_SpinboxCalefaccion, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_SpinboxCalefaccion, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_SpinboxCalefaccion, &lv_font_montserrat_48, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_radius(ui_SpinboxCalefaccion, 5, LV_PART_CURSOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_SpinboxCalefaccion, lv_color_hex(0x3F009C), LV_PART_CURSOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_SpinboxCalefaccion, 255, LV_PART_CURSOR | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_SpinboxCalefaccion, lv_color_hex(0xFFFFFF), LV_PART_CURSOR | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_SpinboxCalefaccion, 255, LV_PART_CURSOR | LV_STATE_DEFAULT);

    ui_Container2 = lv_obj_create(ui_ConfiguracionesUsuario);
    lv_obj_remove_style_all(ui_Container2);
    lv_obj_set_width(ui_Container2, 282);
    lv_obj_set_height(ui_Container2, 92);
    lv_obj_set_x(ui_Container2, -20);
    lv_obj_set_y(ui_Container2, 75);
    lv_obj_set_align(ui_Container2, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_Container2, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_ACSMas = lv_button_create(ui_Container2);
    lv_obj_set_width(ui_ACSMas, 75);
    lv_obj_set_height(ui_ACSMas, 65);
    lv_obj_set_x(ui_ACSMas, -105);
    lv_obj_set_y(ui_ACSMas, 0);
    lv_obj_set_align(ui_ACSMas, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ACSMas, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_ACSMas, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_ACSMas, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ACSMas, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_ACSMas, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_ACSMas, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label19 = lv_label_create(ui_ACSMas);
    lv_obj_set_width(ui_Label19, 30);
    lv_obj_set_height(ui_Label19, 39);
    lv_obj_set_align(ui_Label19, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label19, LV_SYMBOL_PLUS);
    lv_obj_set_style_text_color(ui_Label19, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label19, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_Label19, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label19, &lv_font_montserrat_30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ACSMenos = lv_button_create(ui_Container2);
    lv_obj_set_width(ui_ACSMenos, 75);
    lv_obj_set_height(ui_ACSMenos, 65);
    lv_obj_set_x(ui_ACSMenos, 105);
    lv_obj_set_y(ui_ACSMenos, 0);
    lv_obj_set_align(ui_ACSMenos, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ACSMenos, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_ACSMenos, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_ACSMenos, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ACSMenos, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_ACSMenos, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_ACSMenos, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label13 = lv_label_create(ui_ACSMenos);
    lv_obj_set_width(ui_Label13, 30);
    lv_obj_set_height(ui_Label13, 39);
    lv_obj_set_align(ui_Label13, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label13, LV_SYMBOL_MINUS);
    lv_obj_set_style_text_color(ui_Label13, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label13, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_Label13, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label13, &lv_font_montserrat_30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SpinboxACS = lv_spinbox_create(ui_Container2);
    lv_obj_set_width(ui_SpinboxACS, 150);
    lv_obj_set_height(ui_SpinboxACS, 80);
    lv_obj_set_align(ui_SpinboxACS, LV_ALIGN_CENTER);
    lv_spinbox_set_digit_format(ui_SpinboxACS, 3, 2);
    lv_spinbox_set_range(ui_SpinboxACS, 0, 999);
    lv_spinbox_set_cursor_pos(ui_SpinboxACS, 1 - 1);
    lv_obj_set_style_text_color(ui_SpinboxACS, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_SpinboxACS, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_SpinboxACS, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_SpinboxACS, &lv_font_montserrat_48, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_radius(ui_SpinboxACS, 5, LV_PART_CURSOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_SpinboxACS, lv_color_hex(0x3F009C), LV_PART_CURSOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_SpinboxACS, 255, LV_PART_CURSOR | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_SpinboxACS, lv_color_hex(0xFFFFFF), LV_PART_CURSOR | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_SpinboxACS, 255, LV_PART_CURSOR | LV_STATE_DEFAULT);

    ui_ImageConfigAcs = lv_image_create(ui_ConfiguracionesUsuario);
    lv_image_set_src(ui_ImageConfigAcs, &ui_img_icono_acs_encendida_png);
    lv_obj_set_width(ui_ImageConfigAcs, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ImageConfigAcs, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ImageConfigAcs, 180);
    lv_obj_set_y(ui_ImageConfigAcs, 75);
    lv_obj_set_align(ui_ImageConfigAcs, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ImageConfigAcs, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_ImageConfigAcs, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_ButtonVolverConfiguracionUsuario = lv_button_create(ui_ConfiguracionesUsuario);
    lv_obj_set_width(ui_ButtonVolverConfiguracionUsuario, 65);
    lv_obj_set_height(ui_ButtonVolverConfiguracionUsuario, 100);
    lv_obj_set_x(ui_ButtonVolverConfiguracionUsuario, -213);
    lv_obj_set_y(ui_ButtonVolverConfiguracionUsuario, 0);
    lv_obj_set_align(ui_ButtonVolverConfiguracionUsuario, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ButtonVolverConfiguracionUsuario, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_ButtonVolverConfiguracionUsuario, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_ButtonVolverConfiguracionUsuario, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_ButtonVolverConfiguracionUsuario, lv_color_hex(0x39009C), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ButtonVolverConfiguracionUsuario, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelVolverConfiguracionUsuario = lv_label_create(ui_ButtonVolverConfiguracionUsuario);
    lv_obj_set_width(ui_LabelVolverConfiguracionUsuario, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelVolverConfiguracionUsuario, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_LabelVolverConfiguracionUsuario, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelVolverConfiguracionUsuario, LV_SYMBOL_PREV);
    lv_obj_set_style_text_font(ui_LabelVolverConfiguracionUsuario, &lv_font_montserrat_30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ButtonCalefaccion = lv_button_create(ui_ConfiguracionesUsuario);
    lv_obj_set_width(ui_ButtonCalefaccion, 88);
    lv_obj_set_height(ui_ButtonCalefaccion, 90);
    lv_obj_set_x(ui_ButtonCalefaccion, 180);
    lv_obj_set_y(ui_ButtonCalefaccion, -40);
    lv_obj_set_align(ui_ButtonCalefaccion, LV_ALIGN_CENTER);
    lv_obj_add_state(ui_ButtonCalefaccion, LV_STATE_CHECKED);       /// States
    lv_obj_add_flag(ui_ButtonCalefaccion, LV_OBJ_FLAG_CHECKABLE | LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_ButtonCalefaccion, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_ButtonCalefaccion, lv_color_hex(0x973D3D), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ButtonCalefaccion, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_ButtonCalefaccion, lv_color_hex(0x973D3D), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_ButtonCalefaccion, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_ButtonCalefaccion, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_ButtonCalefaccion, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_ButtonCalefaccion, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_ButtonCalefaccion, lv_color_hex(0x59BA4B), LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_bg_opa(ui_ButtonCalefaccion, 0, LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_border_color(ui_ButtonCalefaccion, lv_color_hex(0x59BA4B), LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_border_opa(ui_ButtonCalefaccion, 255, LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_border_width(ui_ButtonCalefaccion, 5, LV_PART_MAIN | LV_STATE_CHECKED);

    ui_ImageConfigCalefaccion = lv_image_create(ui_ButtonCalefaccion);
    lv_image_set_src(ui_ImageConfigCalefaccion, &ui_img_icono_calefaccion_encendida_png);
    lv_obj_set_width(ui_ImageConfigCalefaccion, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ImageConfigCalefaccion, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_ImageConfigCalefaccion, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_ImageConfigCalefaccion,
                       LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE |
                       LV_OBJ_FLAG_SCROLLABLE);     /// Flags

    ui_ImageLogoConfigsUsuario = lv_image_create(ui_ConfiguracionesUsuario);
    lv_image_set_src(ui_ImageLogoConfigsUsuario, &ui_img_logo_flowing_blanco90_png);
    lv_obj_set_width(ui_ImageLogoConfigsUsuario, 150);
    lv_obj_set_height(ui_ImageLogoConfigsUsuario, 40);
    lv_obj_set_x(ui_ImageLogoConfigsUsuario, -162);
    lv_obj_set_y(ui_ImageLogoConfigsUsuario, 137);
    lv_obj_set_align(ui_ImageLogoConfigsUsuario, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ImageLogoConfigsUsuario, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_ImageLogoConfigsUsuario, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_image_set_scale(ui_ImageLogoConfigsUsuario, 100);

    ui_LabelTituloConfigsUsuario = lv_label_create(ui_ConfiguracionesUsuario);
    lv_obj_set_width(ui_LabelTituloConfigsUsuario, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelTituloConfigsUsuario, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelTituloConfigsUsuario, 0);
    lv_obj_set_y(ui_LabelTituloConfigsUsuario, -123);
    lv_obj_set_align(ui_LabelTituloConfigsUsuario, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelTituloConfigsUsuario, "CONFIGURACIONES DE TEMPERATURA");
    lv_obj_set_style_text_color(ui_LabelTituloConfigsUsuario, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelTituloConfigsUsuario, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelTituloConfigsUsuario, &lv_font_montserrat_22, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_CalefacionMas, ui_event_CalefacionMas, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_CalefaccionMenos, ui_event_CalefaccionMenos, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_SpinboxCalefaccion, ui_event_SpinboxCalefaccion, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_ACSMas, ui_event_ACSMas, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_ACSMenos, ui_event_ACSMenos, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_SpinboxACS, ui_event_SpinboxACS, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_ButtonVolverConfiguracionUsuario, ui_event_ButtonVolverConfiguracionUsuario, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_ButtonCalefaccion, ui_event_ButtonCalefaccion, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_ImageLogoConfigsUsuario, ui_event_ImageLogoConfigsUsuario, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_ConfiguracionesUsuario, ui_event_ConfiguracionesUsuario, LV_EVENT_ALL, NULL);

}
