// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 9.1.0
// Project name: SquareLine_Project2

#include "ui.h"

void ui_ConfiguracionesAvanzadas_screen_init(void)
{
    ui_ConfiguracionesAvanzadas = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_ConfiguracionesAvanzadas, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_ConfiguracionesAvanzadas, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ConfiguracionesAvanzadas, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ContainerSpinbox1 = lv_obj_create(ui_ConfiguracionesAvanzadas);
    lv_obj_remove_style_all(ui_ContainerSpinbox1);
    lv_obj_set_width(ui_ContainerSpinbox1, 300);
    lv_obj_set_height(ui_ContainerSpinbox1, 95);
    lv_obj_set_x(ui_ContainerSpinbox1, 0);
    lv_obj_set_y(ui_ContainerSpinbox1, -20);
    lv_obj_set_align(ui_ContainerSpinbox1, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_ContainerSpinbox1, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_botonMasSpinbox1 = lv_button_create(ui_ContainerSpinbox1);
    lv_obj_set_width(ui_botonMasSpinbox1, 75);
    lv_obj_set_height(ui_botonMasSpinbox1, 65);
    lv_obj_set_x(ui_botonMasSpinbox1, -100);
    lv_obj_set_y(ui_botonMasSpinbox1, 0);
    lv_obj_set_align(ui_botonMasSpinbox1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_botonMasSpinbox1, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_botonMasSpinbox1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_botonMasSpinbox1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_botonMasSpinbox1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_botonMasSpinbox1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_botonMasSpinbox1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelMasSpinbox1 = lv_label_create(ui_botonMasSpinbox1);
    lv_obj_set_width(ui_LabelMasSpinbox1, 30);
    lv_obj_set_height(ui_LabelMasSpinbox1, 39);
    lv_obj_set_align(ui_LabelMasSpinbox1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelMasSpinbox1, "+");
    lv_obj_set_style_text_color(ui_LabelMasSpinbox1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelMasSpinbox1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_LabelMasSpinbox1, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelMasSpinbox1, &lv_font_montserrat_30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_botonMenosSpinbox1 = lv_button_create(ui_ContainerSpinbox1);
    lv_obj_set_width(ui_botonMenosSpinbox1, 75);
    lv_obj_set_height(ui_botonMenosSpinbox1, 65);
    lv_obj_set_x(ui_botonMenosSpinbox1, 100);
    lv_obj_set_y(ui_botonMenosSpinbox1, 0);
    lv_obj_set_align(ui_botonMenosSpinbox1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_botonMenosSpinbox1, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_botonMenosSpinbox1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_botonMenosSpinbox1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_botonMenosSpinbox1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_botonMenosSpinbox1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_botonMenosSpinbox1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelMenosSpinbox1 = lv_label_create(ui_botonMenosSpinbox1);
    lv_obj_set_width(ui_LabelMenosSpinbox1, 30);
    lv_obj_set_height(ui_LabelMenosSpinbox1, 39);
    lv_obj_set_align(ui_LabelMenosSpinbox1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelMenosSpinbox1, "-");
    lv_obj_set_style_text_color(ui_LabelMenosSpinbox1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelMenosSpinbox1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_LabelMenosSpinbox1, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelMenosSpinbox1, &lv_font_montserrat_30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Spinbox1 = lv_spinbox_create(ui_ContainerSpinbox1);
    lv_obj_set_width(ui_Spinbox1, 150);
    lv_obj_set_height(ui_Spinbox1, 80);
    lv_obj_set_align(ui_Spinbox1, LV_ALIGN_CENTER);
    lv_spinbox_set_digit_format(ui_Spinbox1, 3, 2);
    lv_spinbox_set_range(ui_Spinbox1, 0, 999);
    lv_spinbox_set_cursor_pos(ui_Spinbox1, 1 - 1);
    lv_obj_set_style_text_color(ui_Spinbox1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Spinbox1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_Spinbox1, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Spinbox1, &lv_font_montserrat_48, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_radius(ui_Spinbox1, 5, LV_PART_CURSOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Spinbox1, lv_color_hex(0x3F009C), LV_PART_CURSOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Spinbox1, 255, LV_PART_CURSOR | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_Spinbox1, lv_color_hex(0xFFFFFF), LV_PART_CURSOR | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Spinbox1, 255, LV_PART_CURSOR | LV_STATE_DEFAULT);

    ui_ContainerSpinbox2 = lv_obj_create(ui_ConfiguracionesAvanzadas);
    lv_obj_remove_style_all(ui_ContainerSpinbox2);
    lv_obj_set_width(ui_ContainerSpinbox2, 300);
    lv_obj_set_height(ui_ContainerSpinbox2, 95);
    lv_obj_set_x(ui_ContainerSpinbox2, 0);
    lv_obj_set_y(ui_ContainerSpinbox2, 100);
    lv_obj_set_align(ui_ContainerSpinbox2, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_ContainerSpinbox2, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_botonMasSpinbox2 = lv_button_create(ui_ContainerSpinbox2);
    lv_obj_set_width(ui_botonMasSpinbox2, 75);
    lv_obj_set_height(ui_botonMasSpinbox2, 65);
    lv_obj_set_x(ui_botonMasSpinbox2, -100);
    lv_obj_set_y(ui_botonMasSpinbox2, 0);
    lv_obj_set_align(ui_botonMasSpinbox2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_botonMasSpinbox2, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_botonMasSpinbox2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_botonMasSpinbox2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_botonMasSpinbox2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_botonMasSpinbox2, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_botonMasSpinbox2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelMasSpinbox2 = lv_label_create(ui_botonMasSpinbox2);
    lv_obj_set_width(ui_LabelMasSpinbox2, 30);
    lv_obj_set_height(ui_LabelMasSpinbox2, 39);
    lv_obj_set_align(ui_LabelMasSpinbox2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelMasSpinbox2, "+");
    lv_obj_set_style_text_color(ui_LabelMasSpinbox2, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelMasSpinbox2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_LabelMasSpinbox2, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelMasSpinbox2, &lv_font_montserrat_30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_botonMenosSpinbox2 = lv_button_create(ui_ContainerSpinbox2);
    lv_obj_set_width(ui_botonMenosSpinbox2, 75);
    lv_obj_set_height(ui_botonMenosSpinbox2, 65);
    lv_obj_set_x(ui_botonMenosSpinbox2, 100);
    lv_obj_set_y(ui_botonMenosSpinbox2, 0);
    lv_obj_set_align(ui_botonMenosSpinbox2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_botonMenosSpinbox2, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_botonMenosSpinbox2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_botonMenosSpinbox2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_botonMenosSpinbox2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_botonMenosSpinbox2, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_botonMenosSpinbox2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelMenosSpinbox2 = lv_label_create(ui_botonMenosSpinbox2);
    lv_obj_set_width(ui_LabelMenosSpinbox2, 30);
    lv_obj_set_height(ui_LabelMenosSpinbox2, 39);
    lv_obj_set_align(ui_LabelMenosSpinbox2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelMenosSpinbox2, "-");
    lv_obj_set_style_text_color(ui_LabelMenosSpinbox2, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelMenosSpinbox2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_LabelMenosSpinbox2, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelMenosSpinbox2, &lv_font_montserrat_30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Spinbox2 = lv_spinbox_create(ui_ContainerSpinbox2);
    lv_obj_set_width(ui_Spinbox2, 150);
    lv_obj_set_height(ui_Spinbox2, 80);
    lv_obj_set_align(ui_Spinbox2, LV_ALIGN_CENTER);
    lv_spinbox_set_digit_format(ui_Spinbox2, 3, 2);
    lv_spinbox_set_range(ui_Spinbox2, 0, 999);
    lv_spinbox_set_cursor_pos(ui_Spinbox2, 1 - 1);
    lv_obj_set_style_text_color(ui_Spinbox2, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Spinbox2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_Spinbox2, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Spinbox2, &lv_font_montserrat_48, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_radius(ui_Spinbox2, 5, LV_PART_CURSOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Spinbox2, lv_color_hex(0x3F009C), LV_PART_CURSOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Spinbox2, 255, LV_PART_CURSOR | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_Spinbox2, lv_color_hex(0xFFFFFF), LV_PART_CURSOR | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Spinbox2, 255, LV_PART_CURSOR | LV_STATE_DEFAULT);

    ui_ButtonCambioDerecha = lv_button_create(ui_ConfiguracionesAvanzadas);
    lv_obj_set_width(ui_ButtonCambioDerecha, 65);
    lv_obj_set_height(ui_ButtonCambioDerecha, 100);
    lv_obj_set_x(ui_ButtonCambioDerecha, -213);
    lv_obj_set_y(ui_ButtonCambioDerecha, 80);
    lv_obj_set_align(ui_ButtonCambioDerecha, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ButtonCambioDerecha, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_ButtonCambioDerecha, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_ButtonCambioDerecha, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_ButtonCambioDerecha, lv_color_hex(0x39009C), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ButtonCambioDerecha, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelBoton = lv_label_create(ui_ButtonCambioDerecha);
    lv_obj_set_width(ui_LabelBoton, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelBoton, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_LabelBoton, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelBoton, "D");
    lv_obj_set_style_text_color(ui_LabelBoton, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelBoton, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelBoton, &lv_font_montserrat_30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_DropdownOpciones = lv_dropdown_create(ui_ConfiguracionesAvanzadas);
    lv_dropdown_set_options(ui_DropdownOpciones, "Maximos\nMinimos\nHisteresis\nRetardos");
    lv_obj_set_width(ui_DropdownOpciones, 451);
    lv_obj_set_height(ui_DropdownOpciones, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_DropdownOpciones, 0);
    lv_obj_set_y(ui_DropdownOpciones, -124);
    lv_obj_set_align(ui_DropdownOpciones, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_DropdownOpciones, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_set_style_text_color(ui_DropdownOpciones, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_DropdownOpciones, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_DropdownOpciones, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_DropdownOpciones, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_DropdownOpciones, lv_color_hex(0x39009C), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_DropdownOpciones, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_text_letter_space(lv_dropdown_get_list(ui_DropdownOpciones), 0,  LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_line_space(lv_dropdown_get_list(ui_DropdownOpciones), 40,  LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(lv_dropdown_get_list(ui_DropdownOpciones), &lv_font_montserrat_18,
                               LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ButtonVolverConfiguracionAvanzada = lv_button_create(ui_ConfiguracionesAvanzadas);
    lv_obj_set_width(ui_ButtonVolverConfiguracionAvanzada, 65);
    lv_obj_set_height(ui_ButtonVolverConfiguracionAvanzada, 100);
    lv_obj_set_x(ui_ButtonVolverConfiguracionAvanzada, -213);
    lv_obj_set_y(ui_ButtonVolverConfiguracionAvanzada, -35);
    lv_obj_set_align(ui_ButtonVolverConfiguracionAvanzada, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ButtonVolverConfiguracionAvanzada, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_ButtonVolverConfiguracionAvanzada, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_ButtonVolverConfiguracionAvanzada, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_ButtonVolverConfiguracionAvanzada, lv_color_hex(0x39009C),
                              LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ButtonVolverConfiguracionAvanzada, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelVolverConfiguracionUsuario2 = lv_label_create(ui_ButtonVolverConfiguracionAvanzada);
    lv_obj_set_width(ui_LabelVolverConfiguracionUsuario2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelVolverConfiguracionUsuario2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_LabelVolverConfiguracionUsuario2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelVolverConfiguracionUsuario2, LV_SYMBOL_PREV);
    lv_obj_set_style_text_font(ui_LabelVolverConfiguracionUsuario2, &lv_font_montserrat_30,
                               LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelNombreSpinbox1 = lv_label_create(ui_ConfiguracionesAvanzadas);
    lv_obj_set_width(ui_LabelNombreSpinbox1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelNombreSpinbox1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelNombreSpinbox1, 0);
    lv_obj_set_y(ui_LabelNombreSpinbox1, -75);
    lv_obj_set_align(ui_LabelNombreSpinbox1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelNombreSpinbox1, "CAL");
    lv_obj_set_style_text_color(ui_LabelNombreSpinbox1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelNombreSpinbox1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelNombreSpinbox1, &lv_font_montserrat_30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelNombreSpinbox2 = lv_label_create(ui_ConfiguracionesAvanzadas);
    lv_obj_set_width(ui_LabelNombreSpinbox2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelNombreSpinbox2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelNombreSpinbox2, 0);
    lv_obj_set_y(ui_LabelNombreSpinbox2, 45);
    lv_obj_set_align(ui_LabelNombreSpinbox2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelNombreSpinbox2, "ACS");
    lv_obj_set_style_text_color(ui_LabelNombreSpinbox2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelNombreSpinbox2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelNombreSpinbox2, &lv_font_montserrat_30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_KeyboardCodigo = lv_keyboard_create(ui_ConfiguracionesAvanzadas);
    lv_keyboard_set_mode(ui_KeyboardCodigo, LV_KEYBOARD_MODE_NUMBER);
    lv_obj_set_width(ui_KeyboardCodigo, lv_pct(100));
    lv_obj_set_height(ui_KeyboardCodigo, lv_pct(70));
    lv_obj_set_x(ui_KeyboardCodigo, 0);
    lv_obj_set_y(ui_KeyboardCodigo, 46);
    lv_obj_set_align(ui_KeyboardCodigo, LV_ALIGN_CENTER);
    lv_obj_set_style_bg_color(ui_KeyboardCodigo, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_KeyboardCodigo, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_text_font(ui_KeyboardCodigo, &lv_font_montserrat_26, LV_PART_ITEMS | LV_STATE_DEFAULT);

    ui_Panel2 = lv_obj_create(ui_ConfiguracionesAvanzadas);
    lv_obj_set_width(ui_Panel2, lv_pct(100));
    lv_obj_set_height(ui_Panel2, lv_pct(30));
    lv_obj_set_x(ui_Panel2, 0);
    lv_obj_set_y(ui_Panel2, -113);
    lv_obj_set_align(ui_Panel2, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_Panel2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Panel2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Panel2, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Panel2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_TextAreaCodigo = lv_textarea_create(ui_Panel2);
    lv_obj_set_width(ui_TextAreaCodigo, lv_pct(82));
    lv_obj_set_height(ui_TextAreaCodigo, LV_SIZE_CONTENT);    /// 25
    lv_obj_set_x(ui_TextAreaCodigo, 27);
    lv_obj_set_y(ui_TextAreaCodigo, 3);
    lv_obj_set_align(ui_TextAreaCodigo, LV_ALIGN_CENTER);
    if("0123456789" == "") lv_textarea_set_accepted_chars(ui_TextAreaCodigo, NULL);
    else lv_textarea_set_accepted_chars(ui_TextAreaCodigo, "0123456789");
    lv_textarea_set_max_length(ui_TextAreaCodigo, 4);
    lv_textarea_set_placeholder_text(ui_TextAreaCodigo, "INGRESAR CODIGO . . .");
    lv_textarea_set_one_line(ui_TextAreaCodigo, true);
    lv_textarea_set_password_mode(ui_TextAreaCodigo, true);
    lv_obj_set_style_text_font(ui_TextAreaCodigo, &lv_font_montserrat_30, LV_PART_MAIN | LV_STATE_DEFAULT);



    ui_ButtonIngresoConfigsAvanzadas = lv_button_create(ui_ConfiguracionesAvanzadas);
    lv_obj_set_width(ui_ButtonIngresoConfigsAvanzadas, 65);
    lv_obj_set_height(ui_ButtonIngresoConfigsAvanzadas, 83);
    lv_obj_set_x(ui_ButtonIngresoConfigsAvanzadas, -214);
    lv_obj_set_y(ui_ButtonIngresoConfigsAvanzadas, -113);
    lv_obj_set_align(ui_ButtonIngresoConfigsAvanzadas, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ButtonIngresoConfigsAvanzadas, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_ButtonIngresoConfigsAvanzadas, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_ButtonIngresoConfigsAvanzadas, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_ButtonIngresoConfigsAvanzadas, lv_color_hex(0x39009C), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ButtonIngresoConfigsAvanzadas, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelVolverConfiguracionUsuario4 = lv_label_create(ui_ButtonIngresoConfigsAvanzadas);
    lv_obj_set_width(ui_LabelVolverConfiguracionUsuario4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelVolverConfiguracionUsuario4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_LabelVolverConfiguracionUsuario4, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelVolverConfiguracionUsuario4, LV_SYMBOL_PREV);
    lv_obj_set_style_text_font(ui_LabelVolverConfiguracionUsuario4, &lv_font_montserrat_30,
                               LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_botonMasSpinbox1, ui_event_botonMasSpinbox1, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_botonMenosSpinbox1, ui_event_botonMenosSpinbox1, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Spinbox1, ui_event_Spinbox1, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_botonMasSpinbox2, ui_event_botonMasSpinbox2, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_botonMenosSpinbox2, ui_event_botonMenosSpinbox2, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Spinbox2, ui_event_Spinbox2, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_ButtonCambioDerecha, ui_event_ButtonCambioDerecha, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_DropdownOpciones, ui_event_DropdownOpciones, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_ButtonVolverConfiguracionAvanzada, ui_event_ButtonVolverConfiguracionAvanzada, LV_EVENT_ALL,
                        NULL);
    lv_keyboard_set_textarea(ui_KeyboardCodigo, ui_TextAreaCodigo);
    lv_obj_add_event_cb(ui_KeyboardCodigo, ui_event_KeyboardCodigo, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_ButtonIngresoConfigsAvanzadas, ui_event_ButtonIngresoConfigsAvanzadas, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_ConfiguracionesAvanzadas, ui_event_ConfiguracionesAvanzadas, LV_EVENT_ALL, NULL);

}
