// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 9.1.0
// Project name: SquareLine_Project2

#include "ui.h"

void ui_Diagnostico_screen_init(void)
{
    ui_Diagnostico = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_Diagnostico, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Diagnostico, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Diagnostico, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ButtonVolverDiagnostico = lv_button_create(ui_Diagnostico);
    lv_obj_set_width(ui_ButtonVolverDiagnostico, 65);
    lv_obj_set_height(ui_ButtonVolverDiagnostico, 100);
    lv_obj_set_x(ui_ButtonVolverDiagnostico, -213);
    lv_obj_set_y(ui_ButtonVolverDiagnostico, 0);
    lv_obj_set_align(ui_ButtonVolverDiagnostico, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ButtonVolverDiagnostico, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_ButtonVolverDiagnostico, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_ButtonVolverDiagnostico, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_ButtonVolverDiagnostico, lv_color_hex(0x39009C), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ButtonVolverDiagnostico, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelVolverConfiguracionUsuario3 = lv_label_create(ui_ButtonVolverDiagnostico);
    lv_obj_set_width(ui_LabelVolverConfiguracionUsuario3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelVolverConfiguracionUsuario3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_LabelVolverConfiguracionUsuario3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelVolverConfiguracionUsuario3, LV_SYMBOL_PREV);
    lv_obj_set_style_text_font(ui_LabelVolverConfiguracionUsuario3, &lv_font_montserrat_30,
                               LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BotonEtapa5 = lv_button_create(ui_Diagnostico);
    lv_obj_set_width(ui_BotonEtapa5, 80);
    lv_obj_set_height(ui_BotonEtapa5, 80);
    lv_obj_set_x(ui_BotonEtapa5, 150);
    lv_obj_set_y(ui_BotonEtapa5, 0);
    lv_obj_set_align(ui_BotonEtapa5, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_BotonEtapa5, LV_OBJ_FLAG_CHECKABLE | LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_BotonEtapa5, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_BotonEtapa5, lv_color_hex(0x39009C), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_BotonEtapa5, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_BotonEtapa5, lv_color_hex(0xC52222), LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_bg_opa(ui_BotonEtapa5, 255, LV_PART_MAIN | LV_STATE_CHECKED);

    ui_Label23 = lv_label_create(ui_BotonEtapa5);
    lv_obj_set_width(ui_Label23, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label23, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label23, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label23, "5");
    lv_obj_set_style_text_color(ui_Label23, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label23, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label23, &lv_font_montserrat_30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BotonEtapa6 = lv_button_create(ui_Diagnostico);
    lv_obj_set_width(ui_BotonEtapa6, 80);
    lv_obj_set_height(ui_BotonEtapa6, 80);
    lv_obj_set_x(ui_BotonEtapa6, 150);
    lv_obj_set_y(ui_BotonEtapa6, 100);
    lv_obj_set_align(ui_BotonEtapa6, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_BotonEtapa6, LV_OBJ_FLAG_CHECKABLE | LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_BotonEtapa6, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_BotonEtapa6, lv_color_hex(0x39009C), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_BotonEtapa6, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_BotonEtapa6, lv_color_hex(0xC52222), LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_bg_opa(ui_BotonEtapa6, 255, LV_PART_MAIN | LV_STATE_CHECKED);

    ui_Label22 = lv_label_create(ui_BotonEtapa6);
    lv_obj_set_width(ui_Label22, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label22, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label22, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label22, "6");
    lv_obj_set_style_text_color(ui_Label22, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label22, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label22, &lv_font_montserrat_30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BotonEtapa1 = lv_button_create(ui_Diagnostico);
    lv_obj_set_width(ui_BotonEtapa1, 80);
    lv_obj_set_height(ui_BotonEtapa1, 80);
    lv_obj_set_x(ui_BotonEtapa1, -100);
    lv_obj_set_y(ui_BotonEtapa1, 0);
    lv_obj_set_align(ui_BotonEtapa1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_BotonEtapa1, LV_OBJ_FLAG_CHECKABLE | LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_BotonEtapa1, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_BotonEtapa1, lv_color_hex(0x39009C), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_BotonEtapa1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_BotonEtapa1, lv_color_hex(0xC52222), LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_bg_opa(ui_BotonEtapa1, 255, LV_PART_MAIN | LV_STATE_CHECKED);

    ui_Label11 = lv_label_create(ui_BotonEtapa1);
    lv_obj_set_width(ui_Label11, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label11, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label11, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label11, "1");
    lv_obj_set_style_text_color(ui_Label11, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label11, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label11, &lv_font_montserrat_30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BotonEtapa4 = lv_button_create(ui_Diagnostico);
    lv_obj_set_width(ui_BotonEtapa4, 80);
    lv_obj_set_height(ui_BotonEtapa4, 80);
    lv_obj_set_x(ui_BotonEtapa4, 25);
    lv_obj_set_y(ui_BotonEtapa4, 100);
    lv_obj_set_align(ui_BotonEtapa4, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_BotonEtapa4, LV_OBJ_FLAG_CHECKABLE | LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_BotonEtapa4, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_BotonEtapa4, lv_color_hex(0x39009C), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_BotonEtapa4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_BotonEtapa4, lv_color_hex(0xC52222), LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_bg_opa(ui_BotonEtapa4, 255, LV_PART_MAIN | LV_STATE_CHECKED);

    ui_Label14 = lv_label_create(ui_BotonEtapa4);
    lv_obj_set_width(ui_Label14, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label14, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label14, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label14, "4");
    lv_obj_set_style_text_color(ui_Label14, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label14, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label14, &lv_font_montserrat_30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BotonEtapa3 = lv_button_create(ui_Diagnostico);
    lv_obj_set_width(ui_BotonEtapa3, 80);
    lv_obj_set_height(ui_BotonEtapa3, 80);
    lv_obj_set_x(ui_BotonEtapa3, -100);
    lv_obj_set_y(ui_BotonEtapa3, 100);
    lv_obj_set_align(ui_BotonEtapa3, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_BotonEtapa3, LV_OBJ_FLAG_CHECKABLE | LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_BotonEtapa3, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_BotonEtapa3, lv_color_hex(0x39009C), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_BotonEtapa3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_BotonEtapa3, lv_color_hex(0xC52222), LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_bg_opa(ui_BotonEtapa3, 255, LV_PART_MAIN | LV_STATE_CHECKED);

    ui_Label21 = lv_label_create(ui_BotonEtapa3);
    lv_obj_set_width(ui_Label21, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label21, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label21, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label21, "3");
    lv_obj_set_style_text_color(ui_Label21, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label21, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label21, &lv_font_montserrat_30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BotonEtapa2 = lv_button_create(ui_Diagnostico);
    lv_obj_set_width(ui_BotonEtapa2, 80);
    lv_obj_set_height(ui_BotonEtapa2, 80);
    lv_obj_set_x(ui_BotonEtapa2, 25);
    lv_obj_set_y(ui_BotonEtapa2, 0);
    lv_obj_set_align(ui_BotonEtapa2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_BotonEtapa2, LV_OBJ_FLAG_CHECKABLE | LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_BotonEtapa2, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_BotonEtapa2, lv_color_hex(0x39009C), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_BotonEtapa2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_BotonEtapa2, lv_color_hex(0xC52222), LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_bg_opa(ui_BotonEtapa2, 255, LV_PART_MAIN | LV_STATE_CHECKED);

    ui_Label20 = lv_label_create(ui_BotonEtapa2);
    lv_obj_set_width(ui_Label20, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label20, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label20, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label20, "2");
    lv_obj_set_style_text_color(ui_Label20, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label20, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label20, &lv_font_montserrat_30, LV_PART_MAIN | LV_STATE_DEFAULT);
    
    ui_ButtonPurga = lv_button_create(ui_Diagnostico);
    lv_obj_set_width(ui_ButtonPurga, 100);
    lv_obj_set_height(ui_ButtonPurga, 49);
    lv_obj_set_x(ui_ButtonPurga, 150);
    lv_obj_set_y(ui_ButtonPurga, -75);
    lv_obj_set_align(ui_ButtonPurga, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ButtonPurga, LV_OBJ_FLAG_CHECKABLE | LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_ButtonPurga, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_ButtonPurga, lv_color_hex(0x943C39), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ButtonPurga, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_ButtonPurga, lv_color_hex(0x5ABA4A), LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_bg_opa(ui_ButtonPurga, 255, LV_PART_MAIN | LV_STATE_CHECKED);

    ui_Label6 = lv_label_create(ui_ButtonPurga);
    lv_obj_set_width(ui_Label6, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label6, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label6, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label6, "BOMBAS\nPURGA");
    lv_obj_set_style_text_color(ui_Label6, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label6, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_Label6, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label1 = lv_label_create(ui_Diagnostico);
    lv_obj_set_width(ui_Label1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label1, -40);
    lv_obj_set_y(ui_Label1, -75);
    lv_obj_set_align(ui_Label1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label1, "TESTEO DE SALIDAS");
    lv_obj_set_style_text_color(ui_Label1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label1, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_CheckboxDiagnostico = lv_checkbox_create(ui_Diagnostico);
    lv_checkbox_set_text(ui_CheckboxDiagnostico, "DIAGNOSTICO");
    lv_obj_set_width(ui_CheckboxDiagnostico, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_CheckboxDiagnostico, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_CheckboxDiagnostico, 0);
    lv_obj_set_y(ui_CheckboxDiagnostico, -121);
    lv_obj_set_align(ui_CheckboxDiagnostico, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_CheckboxDiagnostico, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_set_style_text_color(ui_CheckboxDiagnostico, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_CheckboxDiagnostico, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_CheckboxDiagnostico, &lv_font_montserrat_34, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_radius(ui_CheckboxDiagnostico, 5, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_CheckboxDiagnostico, lv_color_hex(0x943C39), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_CheckboxDiagnostico, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_CheckboxDiagnostico, lv_color_hex(0x39009C), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_CheckboxDiagnostico, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_CheckboxDiagnostico, 0, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_CheckboxDiagnostico, 10, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_CheckboxDiagnostico, 10, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_CheckboxDiagnostico, 10, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_CheckboxDiagnostico, 10, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_CheckboxDiagnostico, lv_color_hex(0x5ABA4A), LV_PART_INDICATOR | LV_STATE_CHECKED);
    lv_obj_set_style_bg_opa(ui_CheckboxDiagnostico, 255, LV_PART_INDICATOR | LV_STATE_CHECKED);
    lv_obj_set_style_border_width(ui_CheckboxDiagnostico, 0, LV_PART_INDICATOR | LV_STATE_CHECKED);

    lv_obj_add_event_cb(ui_ButtonVolverDiagnostico, ui_event_ButtonVolverDiagnostico, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_BotonEtapa5, ui_event_BotonEtapa5, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_BotonEtapa6, ui_event_BotonEtapa6, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_BotonEtapa1, ui_event_BotonEtapa1, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_BotonEtapa4, ui_event_BotonEtapa4, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_BotonEtapa3, ui_event_BotonEtapa3, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_BotonEtapa2, ui_event_BotonEtapa2, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_ButtonPurga, ui_event_ButtonPurga, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_CheckboxDiagnostico, ui_event_CheckboxDiagnostico, LV_EVENT_ALL, NULL);

}
