// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 9.1.0
// Project name: SquareLine_Project2

#ifndef _UI_EVENTS_H
#define _UI_EVENTS_H

#ifdef __cplusplus
extern "C" {
#endif

enum Opcion{
	MAXIMOS,
	MINIMOS,
	HISTERESIS,
	RETARDOS
};


// PRINCIPAL
void restartESP32(lv_event_t * e);
void camibarEstadoCalefaccion(lv_event_t * e);
void CambiarEstadoCaldera(lv_event_t * e);
void cargarValoresSP(lv_event_t * e);

// CONFIGURACIONES DE USUARIO
void cargarValoresConfigUsuario(lv_event_t * e);
void cambiarConfigTempCalefaccion(lv_event_t * e);
void cambiarConfigTempACS(lv_event_t * e);

// ALARMAS
void cargarValoresAlarmas(lv_event_t * e);
void borrarAlarmas(lv_event_t * e);

// CONFIGURACIONES AVANZADAS
void cargarValoresCodigoIngreso(lv_event_t * e);
void verificarCodigo(lv_event_t * e);
void SeleccionConfiguracionesAvanzadas(lv_event_t * e);
void cambiarConfigSpinbox1(lv_event_t * e);
void cambiarConfigSpinbox2(lv_event_t * e);

// DIAGNOSTICO
void cambiarEstadoDiagnostico(lv_event_t * e);
void pruebaSalidas(lv_event_t * e);
void purga(lv_event_t * e);

// ALERTAS
void volverDeAlerta(lv_event_t * e);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
