// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 9.1.0
// Project name: SquareLine_Project2

#include "ui.h"

// ----- Funciones auxiliares -----
 
const char* obtenerLabelAlarmaUI(causaAlarma_t causa);

// --------------------------------

const char codigo[4] = "0000";

void cargarValoresConfigUsuario(lv_event_t * e){
	int val;

  // VALOR Y RANGO PARA EL SPINBOX DE CONFIGURACION DE TEMPERATURA DE CALEFACCION
  val = configuracionesUI_->temperaturaCalefaccion * 10;
  lv_spinbox_set_value(ui_SpinboxCalefaccion, val);
  lv_spinbox_set_range(ui_SpinboxCalefaccion, configuracionesUI_->temperaturaCalefaccionMinimo*10, configuracionesUI_->temperaturaCalefaccionMaximo*10);
  
  // // VALOR Y RANGO PARA EL SPINBOX DE CONFIGURACION DE TEMPERATURA DE CALEFACCION
  val = configuracionesUI_->temperaturaACS * 10;
  lv_spinbox_set_value(ui_SpinboxACS, val);
  lv_spinbox_set_range(ui_SpinboxACS, configuracionesUI_->temperaturaACSMinimo*10, configuracionesUI_->temperaturaACSMaximo*10);
}

void cargarValoresCodigoIngreso(lv_event_t * e){

	lv_textarea_set_text(ui_TextAreaCodigo, "");
	lv_textarea_set_placeholder_text(ui_TextAreaCodigo, "INGRESAR CODIGO . . .");

	lv_obj_clear_flag(ui_Panel2,LV_OBJ_FLAG_HIDDEN);
	lv_obj_clear_flag(ui_TextAreaCodigo,LV_OBJ_FLAG_HIDDEN);
	lv_obj_clear_flag(ui_KeyboardCodigo,LV_OBJ_FLAG_HIDDEN);
	lv_obj_clear_flag(ui_ButtonIngresoConfigsAvanzadas,LV_OBJ_FLAG_HIDDEN);
}

void camibarEstadoCalefaccion(lv_event_t * e){
	bool toggleCalefaccion = !configuracionesUI_->calefaccionOn;
	guardarConfigsNVS(CALEFACCION_ON, &toggleCalefaccion, sizeof(toggleCalefaccion));
}

void CambiarEstadoCaldera(lv_event_t * e){
	bool toggleEncendido = !configuracionesUI_->encendidoOn;
	guardarConfigsNVS(ENCENDIDO_ON, &toggleEncendido, sizeof(toggleEncendido));
}

void cargarValoresSP(lv_event_t * e){
	char buffer[15];

  // SP TEMPERATURA DE CALEFACCION
  if (configuracionesUI_->calefaccionOn == true){
  	snprintf(buffer, sizeof(buffer), "%.1f °C\nON", configuracionesUI_->temperaturaCalefaccion);
  } else {
  	snprintf(buffer, sizeof(buffer), "%.1f °C\nOFF", configuracionesUI_->temperaturaCalefaccion);
  }
  lv_label_set_text(ui_LabelTempSPCal, buffer);
  
  // SP TEMPERATURA DE ACS
  snprintf(buffer, sizeof(buffer), "%.1f °C", configuracionesUI_->temperaturaACS);
  lv_label_set_text(ui_LabelTempSPAcs, buffer);
  
}

void cambiarConfigTempCalefaccion(lv_event_t * e){
  float tempConfig = lv_spinbox_get_value(ui_SpinboxCalefaccion)/10.0;
  guardarConfigsNVS(TEMP_CALEFACCION, &tempConfig, sizeof(tempConfig));
}

void cambiarConfigTempACS(lv_event_t * e){
  float tempConfig = lv_spinbox_get_value(ui_SpinboxACS)/10.0;
  guardarConfigsNVS(TEMP_ACS, &tempConfig, sizeof(tempConfig));
}

void cambiarEstadoDiagnostico(lv_event_t * e){

	if (*estadoControlUI_ == ALARMA){
		lv_obj_clear_state(ui_CheckboxDiagnostico, LV_STATE_CHECKED);
		return;
	}

	bool toggleDiagnostico = !configuracionesUI_->diagnosticoOn;
	guardarConfigsNVS(DIAGNOSTICO_ON, &toggleDiagnostico, sizeof(toggleDiagnostico));

	// Activo los botones
	if (toggleDiagnostico == true){

		lv_obj_clear_flag(ui_LabelDiagnosticoPrincipal, LV_OBJ_FLAG_HIDDEN);

		lv_obj_add_flag(ui_BotonEtapa1, LV_OBJ_FLAG_CLICKABLE);
		lv_obj_add_flag(ui_BotonEtapa2, LV_OBJ_FLAG_CLICKABLE);
		lv_obj_add_flag(ui_BotonEtapa3, LV_OBJ_FLAG_CLICKABLE);
		lv_obj_add_flag(ui_BotonEtapa4, LV_OBJ_FLAG_CLICKABLE);

		lv_obj_add_flag(ui_ButtonPurga, LV_OBJ_FLAG_CLICKABLE);
		lv_obj_add_flag(ui_BotonEtapa5, LV_OBJ_FLAG_CLICKABLE);
		lv_obj_add_flag(ui_BotonEtapa6, LV_OBJ_FLAG_CLICKABLE);
	}

	else {
		
		lv_obj_add_flag(ui_LabelDiagnosticoPrincipal, LV_OBJ_FLAG_HIDDEN);

		lv_obj_clear_flag(ui_BotonEtapa1, LV_OBJ_FLAG_CLICKABLE);
		lv_obj_clear_state(ui_BotonEtapa1, LV_STATE_CHECKED);
		lv_obj_clear_flag(ui_BotonEtapa2, LV_OBJ_FLAG_CLICKABLE);
		lv_obj_clear_state(ui_BotonEtapa2, LV_STATE_CHECKED);
		lv_obj_clear_flag(ui_BotonEtapa3, LV_OBJ_FLAG_CLICKABLE);
		lv_obj_clear_state(ui_BotonEtapa3, LV_STATE_CHECKED);
		lv_obj_clear_flag(ui_BotonEtapa4, LV_OBJ_FLAG_CLICKABLE);
		lv_obj_clear_state(ui_BotonEtapa4, LV_STATE_CHECKED);


		lv_obj_clear_flag(ui_ButtonPurga, LV_OBJ_FLAG_CLICKABLE);
		lv_obj_clear_state(ui_ButtonPurga, LV_STATE_CHECKED);
		lv_obj_clear_flag(ui_BotonEtapa5, LV_OBJ_FLAG_CLICKABLE);
		lv_obj_clear_state(ui_BotonEtapa5, LV_STATE_CHECKED);
		lv_obj_clear_flag(ui_BotonEtapa6, LV_OBJ_FLAG_CLICKABLE);
		lv_obj_clear_state(ui_BotonEtapa6, LV_STATE_CHECKED);

	}
}

void verificarCodigo(lv_event_t * e){


	bool codigoCorrecto = true;

	const char* codigoIntroducido = lv_textarea_get_text(ui_TextAreaCodigo);
	for (int i=0; i<4; i++){
		if (codigoIntroducido[i] != codigo[i]){
			codigoCorrecto = false;
			break;
		}
	}

	if (codigoCorrecto){
		lv_obj_add_flag(ui_Panel2,LV_OBJ_FLAG_HIDDEN);
		lv_obj_add_flag(ui_TextAreaCodigo,LV_OBJ_FLAG_HIDDEN);
		lv_obj_add_flag(ui_KeyboardCodigo,LV_OBJ_FLAG_HIDDEN);
		lv_obj_add_flag(ui_ButtonIngresoConfigsAvanzadas,LV_OBJ_FLAG_HIDDEN);
	
	} 

	else {
		lv_textarea_set_text(ui_TextAreaCodigo, "");
		lv_textarea_set_placeholder_text(ui_TextAreaCodigo, "CODIGO INCORRECTO");
	}
}


void cambiarConfigSpinbox1(lv_event_t * e){

  float tempConfigFloat = lv_spinbox_get_value(ui_Spinbox1)/10.0;
  uint16_t tempConfigInt = lv_spinbox_get_value(ui_Spinbox1)*100;

	switch (lv_dropdown_get_selected(ui_DropdownOpciones)){
		case MAXIMOS:
			guardarConfigsNVS(TEMP_CALEFACCION_MAX, &tempConfigFloat, sizeof(tempConfigFloat));
			break;

		case MINIMOS:
			guardarConfigsNVS(TEMP_CALEFACCION_MIN, &tempConfigFloat, sizeof(tempConfigFloat));
			break;

		case HISTERESIS:
			guardarConfigsNVS(HISTERESIS_CALEFACCION, &tempConfigFloat, sizeof(tempConfigFloat));
			break;

		case RETARDOS:
			guardarConfigsNVS(RETARDO_ENCENDIDO, &tempConfigInt, sizeof(tempConfigInt));
			break;
	}
}

void cambiarConfigSpinbox2(lv_event_t * e){

  float tempConfigFloat = lv_spinbox_get_value(ui_Spinbox2)/10.0;
  uint16_t tempConfigInt = lv_spinbox_get_value(ui_Spinbox2)*100;

	switch (lv_dropdown_get_selected(ui_DropdownOpciones)){
		case MAXIMOS:
			guardarConfigsNVS(TEMP_ACS_MAX, &tempConfigFloat, sizeof(tempConfigFloat));
			break;

		case MINIMOS:
			guardarConfigsNVS(TEMP_ACS_MIN, &tempConfigFloat, sizeof(tempConfigFloat));
			break;

		case HISTERESIS:
			guardarConfigsNVS(HISTERESIS_ACS, &tempConfigFloat, sizeof(tempConfigFloat));
			break;

		case RETARDOS:
			guardarConfigsNVS(RETARDO_APAGADO, &tempConfigInt, sizeof(tempConfigInt));
			break;
	}
}

void cargarValoresAlarmas(lv_event_t * e){
	lv_obj_t *LabelsAlarma[5] = {ui_Alarma1, ui_Alarma2, ui_Alarma3, ui_Alarma4, ui_Alarma5};
  bool registro = false;
  
  // Si hay alarmas agrego los labels de los errores y oculto el que indica que no hay errores
  for (int i=0;i < 5;i++){
    if (alarmasUI_[i] != 0){ 
      const char* mensajeError = obtenerLabelAlarmaUI((causaAlarma_t) alarmasUI_[i]);
      lv_label_set_text_fmt(LabelsAlarma[i], "%d. %s\n", i+1, mensajeError);
      lv_obj_remove_flag(LabelsAlarma[i], LV_OBJ_FLAG_HIDDEN);
      registro = true;
    } else{
    	lv_obj_add_flag(LabelsAlarma[i], LV_OBJ_FLAG_HIDDEN);
    }
  }

  if (registro){
    lv_obj_add_flag(ui_SinAlarma, LV_OBJ_FLAG_HIDDEN);
  }
}

void borrarAlarmas(lv_event_t * e){
	borrarAlarmasNVS();
}

void SeleccionConfiguracionesAvanzadas(lv_event_t * e){
	uint32_t seleccion = lv_dropdown_get_selected(ui_DropdownOpciones);
	char nombreSpinbox1[20], nombreSpinbox2[20];
	int valorSpinbox[2], minimoSpinbox, maximoSpinbox;
	
	switch (seleccion){
		case MAXIMOS:
			strcpy(nombreSpinbox1, "CALEFACCION");
			strcpy(nombreSpinbox2, "ACS");
			minimoSpinbox = 0;
			maximoSpinbox = 1000;
			valorSpinbox[0] = configuracionesUI_->temperaturaCalefaccionMaximo*10;
			valorSpinbox[1] = configuracionesUI_->temperaturaACSMaximo*10;
			break;

		case MINIMOS:
			strcpy(nombreSpinbox1, "CALEFACCION");
			strcpy(nombreSpinbox2, "ACS");
			minimoSpinbox = 0;
			maximoSpinbox = 1000;
			valorSpinbox[0] = configuracionesUI_->temperaturaCalefaccionMinimo*10;
			valorSpinbox[1] = configuracionesUI_->temperaturaACSMinimo*10;
			break;

		case HISTERESIS:
			strcpy(nombreSpinbox1, "CALEFACCION");
			strcpy(nombreSpinbox2, "ACS");
			minimoSpinbox = 0;
			maximoSpinbox = 200;
			valorSpinbox[0] = configuracionesUI_->histeresisCalefaccion*10;
			valorSpinbox[1] = configuracionesUI_->histeresisACS*10;
			break;

		case RETARDOS:
			strcpy(nombreSpinbox1, "ENCENDIDO");
			strcpy(nombreSpinbox2, "APAGADO");
			minimoSpinbox = 0;
			maximoSpinbox = 100;
			valorSpinbox[0] = configuracionesUI_->retardoEncendidoMs*10/1000;
			valorSpinbox[1] = configuracionesUI_->retardoApagadoMs*10/1000;
			break;
	}

	// CAMBIAR LABELS
	lv_label_set_text(ui_LabelNombreSpinbox1, nombreSpinbox1);
	lv_label_set_text(ui_LabelNombreSpinbox2, nombreSpinbox2);

	// CAMBIAR PROPIEDADES SPINBOX (VALOR, LIMITES)
	lv_spinbox_set_range(ui_Spinbox1, minimoSpinbox, maximoSpinbox);
	lv_spinbox_set_value(ui_Spinbox1, valorSpinbox[0]);

	lv_spinbox_set_range(ui_Spinbox2, minimoSpinbox, maximoSpinbox);
	lv_spinbox_set_value(ui_Spinbox2, valorSpinbox[1]);
}

void restartESP32(lv_event_t * e){
	esp_restart();
}

void pruebaSalidas(lv_event_t * e){
	lv_obj_t * obj = lv_event_get_target(e);
	
	if (obj == ui_BotonEtapa1){
		if (lv_obj_has_state(obj, LV_STATE_CHECKED)){

			solicitarDiagnosticoEtapa(0,true);
		} else {
			solicitarDiagnosticoEtapa(0,false);
		}
	}

	if (obj == ui_BotonEtapa2){
		if (lv_obj_has_state(obj, LV_STATE_CHECKED)){
			solicitarDiagnosticoEtapa(1,true);
		} else {
			solicitarDiagnosticoEtapa(1,false);
		}
	}

	if (obj == ui_BotonEtapa3){
		if (lv_obj_has_state(obj, LV_STATE_CHECKED)){
			solicitarDiagnosticoEtapa(2,true);
		} else {
			solicitarDiagnosticoEtapa(2,false);
		}
	}

	if (obj == ui_BotonEtapa4){
		if (lv_obj_has_state(obj, LV_STATE_CHECKED)){
			solicitarDiagnosticoEtapa(3,true);
		} else {
			solicitarDiagnosticoEtapa(3,false);
		}
	}
	if (obj == ui_BotonEtapa5){
		if (lv_obj_has_state(ui_ButtonPurga, LV_STATE_CHECKED)){
			solicitarPurgarBomba(BOMBA_CAL);
		} else {	
				if (lv_obj_has_state(obj, LV_STATE_CHECKED)){
					solicitarDiagnosticoEtapa(4,true);
				} else {
					solicitarDiagnosticoEtapa(4,false);
				}
		}
	}
	if (obj == ui_BotonEtapa6){
		if (lv_obj_has_state(ui_ButtonPurga, LV_STATE_CHECKED)){
			solicitarPurgarBomba(BOMBA_ACS);
		} else {	
				if (lv_obj_has_state(obj, LV_STATE_CHECKED)){
					solicitarDiagnosticoEtapa(5,true);
				} else {
					solicitarDiagnosticoEtapa(5,false);
				}
		}
	}
}

void purga(lv_event_t * e){
	solicitarDiagnosticoEtapa(4,false);
	solicitarDiagnosticoEtapa(5,false);
	lv_obj_clear_state(ui_BotonEtapa5,LV_STATE_CHECKED);
	lv_obj_clear_state(ui_BotonEtapa6,LV_STATE_CHECKED);
}

void volverDeAlerta(lv_event_t * e){
	if (alarmasUI_[0] == BOMBAS_OFF || alarmasUI_[0] == BOMBAS_ON ){
		esp_restart();
	}

	else {
		if (configuracionesUI_->encendidoOn == false){
			_ui_screen_change(&ui_Apagado, LV_SCR_LOAD_ANIM_NONE, 0, 0, &ui_Apagado_screen_init);
		} else {
			_ui_screen_change(&ui_Principal, LV_SCR_LOAD_ANIM_NONE, 0, 0, &ui_Principal_screen_init);
		}
	}
}


// Funcion auxiliar 

const char* obtenerLabelAlarmaUI(causaAlarma_t causa){
  switch (causa){
    case BOMBA_CALEFACCION_ON:  
      return "ENCENDIDO BOMBA CALEFACCION";
      break;
    case BOMBA_AGUA_CALIENTE_ON:    
      return "ENCENDIDO BOMBA ACS";
      break; 
    case BOMBAS_OFF:
      return "APAGADO DE BOMBAS";
      break;
    case BOMBAS_ON:
      return "ENCENDIDO DE BOMBAS";
      break;
    case PRESION_ALTA:
      return "PRESION ALTA";
      break;        
    case PRESION_BAJA:
      return "PRESION BAJA";
      break;
    case TEMPERATURA_ALTA:
      return "TEMPERATURA ALTA";
      break;
    case TEMPERATURA_BAJA:
      return "TEMPERATURA BAJA";
      break;
    case TERMOSTATO_SEGURIDAD:
      return "TERMOSTATO SEGURIDAD";
      break;
    case FALLA_SENSOR_1:
      return "FALLA SENSOR CALDERA";
      break;
    case FALLA_SENSOR_2:
      return "FALLA SENSOR AGUA CALIENTE";
      break;
    case FALLA_SENSOR_I:
      return "FALLA SENSOR DE PRESION";
      break;
    default: "";
  }
}