// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 9.1.0
// Project name: SquareLine_Project2

#include "ui.h"

void ui_Inicio_screen_init(void)
{
    ui_Inicio = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_Inicio, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Inicio, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Inicio, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LogoInicio = lv_image_create(ui_Inicio);
    lv_image_set_src(ui_LogoInicio, &ui_img_logo_flowing_300x80_png);
    lv_obj_set_width(ui_LogoInicio, lv_pct(100));
    lv_obj_set_height(ui_LogoInicio, lv_pct(100));
    lv_obj_set_align(ui_LogoInicio, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_LogoInicio, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_LogoInicio, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_image_set_scale(ui_LogoInicio, 350);

    ui_LabelInicio = lv_label_create(ui_Inicio);
    lv_obj_set_width(ui_LabelInicio, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelInicio, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelInicio, 0);
    lv_obj_set_y(ui_LabelInicio, 100);
    lv_obj_set_align(ui_LabelInicio, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelInicio, "INICIANDO . . .");
    lv_obj_set_style_text_color(ui_LabelInicio, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelInicio, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelInicio, &lv_font_montserrat_26, LV_PART_MAIN | LV_STATE_DEFAULT);

}
