// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 9.1.0
// Project name: SquareLine_Project2

#include "ui.h"

void ui_Principal_screen_init(void)
{
    ui_Principal = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_Principal, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Principal, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Principal, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

       ui_PanelConfiguraciones = lv_obj_create(ui_Principal);
    lv_obj_set_width(ui_PanelConfiguraciones, lv_pct(35));
    lv_obj_set_height(ui_PanelConfiguraciones, lv_pct(70));
    lv_obj_set_x(ui_PanelConfiguraciones, 156);
    lv_obj_set_y(ui_PanelConfiguraciones, 48);
    lv_obj_set_align(ui_PanelConfiguraciones, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_PanelConfiguraciones, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_PanelConfiguraciones, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_PanelConfiguraciones, lv_color_hex(0x4A4A4A), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PanelConfiguraciones, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_PanelConfiguraciones, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_PanelConfiguraciones, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_PanelConfiguraciones, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelSPAcs = lv_label_create(ui_PanelConfiguraciones);
    lv_obj_set_width(ui_LabelSPAcs, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelSPAcs, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelSPAcs, 0);
    lv_obj_set_y(ui_LabelSPAcs, -40);
    lv_obj_set_align(ui_LabelSPAcs, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelSPAcs, "S.P. ACS");
    lv_obj_set_style_text_color(ui_LabelSPAcs, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelSPAcs, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelSPAcs, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelSPCal = lv_label_create(ui_PanelConfiguraciones);
    lv_obj_set_width(ui_LabelSPCal, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelSPCal, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelSPCal, 0);
    lv_obj_set_y(ui_LabelSPCal, 25);
    lv_obj_set_align(ui_LabelSPCal, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelSPCal, "S.P. CAL");
    lv_obj_set_style_text_color(ui_LabelSPCal, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelSPCal, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelSPCal, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelTempSPAcs = lv_label_create(ui_PanelConfiguraciones);
    lv_obj_set_width(ui_LabelTempSPAcs, 113);
    lv_obj_set_height(ui_LabelTempSPAcs, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelTempSPAcs, 0);
    lv_obj_set_y(ui_LabelTempSPAcs, -10);
    lv_obj_set_align(ui_LabelTempSPAcs, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelTempSPAcs, "00.0°C");
    lv_obj_set_style_text_color(ui_LabelTempSPAcs, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelTempSPAcs, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_LabelTempSPAcs, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelTempSPAcs, &lv_font_montserrat_26, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_LabelTempSPAcs, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_LabelTempSPAcs, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_LabelTempSPAcs, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_LabelTempSPAcs, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelTempSPCal = lv_label_create(ui_PanelConfiguraciones);
    lv_obj_set_width(ui_LabelTempSPCal, 113);
    lv_obj_set_height(ui_LabelTempSPCal, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelTempSPCal, 0);
    lv_obj_set_y(ui_LabelTempSPCal, 70);
    lv_obj_set_align(ui_LabelTempSPCal, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelTempSPCal, "00.0°C\nOFF");
    lv_obj_set_style_text_color(ui_LabelTempSPCal, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelTempSPCal, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_LabelTempSPCal, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelTempSPCal, &lv_font_montserrat_26, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_LabelTempSPCal, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_LabelTempSPCal, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_LabelTempSPCal, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_LabelTempSPCal, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelSimboloConfiguracion = lv_label_create(ui_PanelConfiguraciones);
    lv_obj_set_width(ui_LabelSimboloConfiguracion, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelSimboloConfiguracion, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelSimboloConfiguracion, 0);
    lv_obj_set_y(ui_LabelSimboloConfiguracion, -85);
    lv_obj_set_align(ui_LabelSimboloConfiguracion, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelSimboloConfiguracion, LV_SYMBOL_SETTINGS);
    lv_obj_set_style_text_color(ui_LabelSimboloConfiguracion, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelSimboloConfiguracion, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelSimboloConfiguracion, &lv_font_montserrat_36, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PanelValores = lv_obj_create(ui_Principal);
    lv_obj_set_width(ui_PanelValores, lv_pct(65));
    lv_obj_set_height(ui_PanelValores, lv_pct(86));
    lv_obj_set_x(ui_PanelValores, -84);
    lv_obj_set_y(ui_PanelValores, lv_pct(-7));
    lv_obj_set_align(ui_PanelValores, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_PanelValores, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_PanelValores, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_PanelValores, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PanelValores, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_PanelValores, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ArcTemperatura = lv_arc_create(ui_PanelValores);
    lv_obj_set_width(ui_ArcTemperatura, 223);
    lv_obj_set_height(ui_ArcTemperatura, 226);
    lv_obj_set_x(ui_ArcTemperatura, 0);
    lv_obj_set_y(ui_ArcTemperatura, -10);
    lv_obj_set_align(ui_ArcTemperatura, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_ArcTemperatura, LV_OBJ_FLAG_CLICKABLE);      /// Flags
    lv_arc_set_value(ui_ArcTemperatura, 30);
    lv_arc_set_bg_angles(ui_ArcTemperatura, 150, 30);
    lv_obj_set_style_arc_color(ui_ArcTemperatura, lv_color_hex(0x292829), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_ArcTemperatura, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_arc_color(ui_ArcTemperatura, lv_color_hex(0xFFFFFF), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_ArcTemperatura, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_ArcTemperatura, lv_color_hex(0x39009C), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ArcTemperatura, 255, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_ArcTemperatura, lv_color_hex(0x000000), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_ArcTemperatura, 255, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_ArcTemperatura, 1, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_LabelTemperatura = lv_label_create(ui_ArcTemperatura);
    lv_obj_set_width(ui_LabelTemperatura, 175);
    lv_obj_set_height(ui_LabelTemperatura, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelTemperatura, 0);
    lv_obj_set_y(ui_LabelTemperatura, -10);
    lv_obj_set_align(ui_LabelTemperatura, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelTemperatura, "00.0°C");
    lv_obj_set_style_text_color(ui_LabelTemperatura, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelTemperatura, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_LabelTemperatura, LV_TEXT_ALIGN_RIGHT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelTemperatura, &lv_font_montserrat_48, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelPresion = lv_label_create(ui_PanelValores);
    lv_obj_set_width(ui_LabelPresion, 134);
    lv_obj_set_height(ui_LabelPresion, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelPresion, -10);
    lv_obj_set_y(ui_LabelPresion, 20);
    lv_obj_set_align(ui_LabelPresion, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelPresion, "00.0 psi");
    lv_obj_set_style_text_color(ui_LabelPresion, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelPresion, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_LabelPresion, LV_TEXT_ALIGN_RIGHT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelPresion, &lv_font_montserrat_26, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ImageCal = lv_image_create(ui_PanelValores);
    lv_image_set_src(ui_ImageCal, &ui_img_icono_calefaccion_apagada_png);
    lv_obj_set_width(ui_ImageCal, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ImageCal, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ImageCal, -45);
    lv_obj_set_y(ui_ImageCal, 100);
    lv_obj_set_align(ui_ImageCal, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ImageCal, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_ImageCal, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_image_set_scale(ui_ImageCal, 200);

    ui_ImageAcs = lv_image_create(ui_PanelValores);
    lv_image_set_src(ui_ImageAcs, &ui_img_icono_acs_apagada_png);
    lv_obj_set_width(ui_ImageAcs, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ImageAcs, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ImageAcs, 45);
    lv_obj_set_y(ui_ImageAcs, 100);
    lv_obj_set_align(ui_ImageAcs, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ImageAcs, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_ImageAcs, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_image_set_scale(ui_ImageAcs, 200);

    ui_ButtonEncendido = lv_button_create(ui_Principal);
    lv_obj_set_width(ui_ButtonEncendido, lv_pct(35));
    lv_obj_set_height(ui_ButtonEncendido, lv_pct(25));
    lv_obj_set_x(ui_ButtonEncendido, 156);
    lv_obj_set_y(ui_ButtonEncendido, -120);
    lv_obj_set_align(ui_ButtonEncendido, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ButtonEncendido, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_ButtonEncendido,
                       LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE |
                       LV_OBJ_FLAG_SCROLLABLE);     /// Flags
    lv_obj_set_style_radius(ui_ButtonEncendido, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_ButtonEncendido, lv_color_hex(0x39009C), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ButtonEncendido, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_ButtonEncendido, lv_color_hex(0x808080), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_ButtonEncendido, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_ButtonEncendido, 5, LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_radius(ui_ButtonEncendido, 5, LV_PART_MAIN | LV_STATE_PRESSED);

    ui_LabelSimboloPower = lv_label_create(ui_ButtonEncendido);
    lv_obj_set_width(ui_LabelSimboloPower, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelSimboloPower, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_LabelSimboloPower, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelSimboloPower, LV_SYMBOL_POWER);
    lv_obj_set_style_text_color(ui_LabelSimboloPower, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelSimboloPower, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelSimboloPower, &lv_font_montserrat_48, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ButtonAlarma = lv_button_create(ui_PanelValores);
    lv_obj_set_width(ui_ButtonAlarma, 50);
    lv_obj_set_height(ui_ButtonAlarma, 50);
    lv_obj_set_x(ui_ButtonAlarma, 0);
    lv_obj_set_y(ui_ButtonAlarma, -75);
    lv_obj_set_align(ui_ButtonAlarma, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ButtonAlarma, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_ButtonAlarma, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_ButtonAlarma, lv_color_hex(0xC52222), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ButtonAlarma, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelSimboloAlarma = lv_label_create(ui_ButtonAlarma);
    lv_obj_set_width(ui_LabelSimboloAlarma, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelSimboloAlarma, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_LabelSimboloAlarma, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelSimboloAlarma, LV_SYMBOL_WARNING);
    lv_obj_set_style_text_color(ui_LabelSimboloAlarma, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelSimboloAlarma, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelSimboloAlarma, &lv_font_montserrat_30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ImageLogoFlowing = lv_image_create(ui_Principal);
    lv_image_set_src(ui_ImageLogoFlowing, &ui_img_logo_flowing_blanco90_png);
    lv_obj_set_width(ui_ImageLogoFlowing, 150);
    lv_obj_set_height(ui_ImageLogoFlowing, 40);
    lv_obj_set_x(ui_ImageLogoFlowing, -162);
    lv_obj_set_y(ui_ImageLogoFlowing, 137);
    lv_obj_set_align(ui_ImageLogoFlowing, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_ImageLogoFlowing,
                       LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE |
                       LV_OBJ_FLAG_SCROLLABLE);     /// Flags
    lv_image_set_scale(ui_ImageLogoFlowing, 100);

    ui_PanelAlarmas = lv_obj_create(ui_Principal);
    lv_obj_set_width(ui_PanelAlarmas, 106);
    lv_obj_set_height(ui_PanelAlarmas, 70);
    lv_obj_set_x(ui_PanelAlarmas, -199);
    lv_obj_set_y(ui_PanelAlarmas, 81);
    lv_obj_set_align(ui_PanelAlarmas, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_PanelAlarmas, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_PanelAlarmas, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PanelAlarmas, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_PanelAlarmas, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelAlarma = lv_label_create(ui_PanelAlarmas);
    lv_obj_set_width(ui_LabelAlarma, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelAlarma, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_LabelAlarma, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelAlarma, LV_SYMBOL_BELL);
    lv_obj_set_style_text_color(ui_LabelAlarma, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelAlarma, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelAlarma, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelDiagnosticoPrincipal = lv_label_create(ui_Principal);
    lv_obj_set_width(ui_LabelDiagnosticoPrincipal, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelDiagnosticoPrincipal, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelDiagnosticoPrincipal, 35);
    lv_obj_set_y(ui_LabelDiagnosticoPrincipal, -125);
    lv_obj_set_align(ui_LabelDiagnosticoPrincipal, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelDiagnosticoPrincipal, "D");
    lv_obj_set_style_text_color(ui_LabelDiagnosticoPrincipal, lv_color_hex(0xC52020), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelDiagnosticoPrincipal, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelDiagnosticoPrincipal, &lv_font_montserrat_28, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_PanelConfiguraciones, ui_event_PanelConfiguraciones, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_ButtonAlarma, ui_event_ButtonAlarma, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_ButtonEncendido, ui_event_ButtonEncendido, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_PanelAlarmas, ui_event_PanelAlarmas, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Principal, ui_event_Principal, LV_EVENT_ALL, NULL);

}
